package com.google.android.libraries.navigation.internal.km;

import com.google.android.libraries.navigation.internal.yz.ev;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes7.dex */
public enum v {
    AUTO_PAN_MODE_ENABLED(w.MAP_STARTUP_PERFORMANCE),
    BASE_TILE_CACHE_STATE(w.MAP_STARTUP_PERFORMANCE),
    BUCKET_ID(w.LOCATION_ATTRIBUTION),
    COLD_START(w.MAP_STARTUP_PERFORMANCE, w.PERFORMANCE),
    DEVICE_MAX_HEAP_MEGABYTES(w.PERFORMANCE, w.TIMELINE, w.WEBVIEW_APIS),
    DEVICE_ORIENTATION_TIME(w.PLATFORM_UI),
    EXTERNAL_INVOCATION_TYPE(w.MAP_STARTUP_PERFORMANCE, w.PERFORMANCE, w.ENTRY_POINT),
    FIRST_VIEWPORT_STATE(w.MAP_STARTUP_PERFORMANCE),
    GOLDFINGER_UI_RENDERED(w.MAP_STARTUP_PERFORMANCE, w.PERFORMANCE),
    GLOBAL_STYLE_TABLE_STATUS(w.MAP_STARTUP_PERFORMANCE),
    GOLDFINGER_LOAD_STATUS(w.GOLDFINGER_SLICED_BY_LOAD_STATUS),
    GOLDFINGER_COMPLETED_ON_FIRST_FRAME(w.GOLDFINGER_SLICED_BY_LOAD_STATUS),
    PREFETCH_PAGE_DATA_SOURCE(w.HOME_SCREEN_PREFETCH),
    NAVIGATION_STATE(w.VECTOR_SERVING),
    NETWORK_QUALITY_STATE(w.DIRECTIONS),
    NETWORK_TYPE(w.CAR, w.DIRECTIONS, w.MAP, w.MAP_STARTUP_PERFORMANCE, w.MESSAGING, w.NETWORK_QUALITY, w.PARKING, w.PERFORMANCE, w.PLACE_PAGE, w.PLATFORM_INFRASTRUCTURE, w.REQUEST_PERFORMANCE, w.SEARCH, w.SYNC, w.TIMELINE, w.WEBVIEW_APIS),
    EFFECTIVE_NETWORK_QUALITY(w.MAP, w.TIMELINE, w.WEBVIEW_APIS),
    OFFLINE_DATA(w.OFFLINE),
    OFFLINE_STATE(w.CAR, w.MAP, w.OFFLINE, w.VECTOR_SERVING),
    SETTINGS(w.SETTINGS),
    TEST(w.TEST_ONLY),
    TILE_CACHE_STATE(w.MAP_STARTUP_PERFORMANCE),
    ANDROID_AUTO_CLIENT_MODE(w.PERFORMANCE, w.CAR, w.REQUEST_PERFORMANCE, w.NAVIGATION, w.NOTIFICATIONS, w.MAP),
    WEBVIEW_APIS(w.WEBVIEW_APIS),
    NAVIGATION_AND_TRAVEL_MODE(w.CAR, w.MAP, w.PERFORMANCE),
    REQUEST_DOMAIN(w.PLATFORM_INFRASTRUCTURE),
    DARK_MODE_ENABLED(w.MAP, w.MAP_STARTUP_PERFORMANCE, w.PERFORMANCE),
    TIMELINE(w.TIMELINE),
    MAPS_ACTIVITY(w.MAPS_ACTIVITY),
    SUSTAINABILITY_DASHBOARD(w.SUSTAINABILITY_DASHBOARD),
    PERFORMANCE(w.PERFORMANCE),
    NAVLOGS_JOINABLE(w.NAVLOGS_JOINABLE),
    IMPRESS_SUPPORT_CHECKER(w.IMPRESS_SUPPORT_CHECKER),
    MAP(w.MAP);

    v(w... wVarArr) {
        ev.p(wVarArr);
    }
}
