package com.google.android.libraries.navigation.internal.zp;

import com.drew.metadata.exif.ExifDirectoryBase;

/* JADX INFO: Access modifiers changed from: package-private */
/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes7.dex */
public interface p {
    public static final n CM;
    public static final n CN;
    public static final n CO;
    public static final n CP;
    public static final n CQ;
    public static final n CR;
    public static final n CS;
    public static final n CT;
    public static final n CU;
    public static final n CV;
    public static final n CX;
    public static final n CY;
    public static final n CZ;
    public static final n Da;
    public static final n Db;
    public static final n Dc;
    public static final n Dd;
    public static final n De;
    public static final n Df;
    public static final n Dg;
    public static final n Dh;
    public static final n Di;
    public static final n Dj;
    public static final n Dk;
    public static final n Dl;
    public static final n Dm;
    public static final n Dn;
    public static final n Do;
    public static final n E;
    public static final n F;
    public static final n G;
    public static final n H;
    public static final n I;
    public static final n J;
    public static final n K;
    public static final n L;
    public static final n M;
    public static final n N;
    public static final n O;
    public static final n P;
    public static final n Q;
    public static final n R;
    public static final n S;
    public static final n T;
    public static final n U;
    public static final n V;
    public static final n W;
    public static final n X;
    public static final n Y;
    public static final n Z;
    public static final n aA;
    public static final n aB;
    public static final n aC;
    public static final n aD;
    public static final n aE;
    public static final n aF;
    public static final n aG;
    public static final n aH;
    public static final n aI;
    public static final n aJ;
    public static final n aK;
    public static final n aL;
    public static final n aM;
    public static final n aN;
    public static final n aO;
    public static final n aP;
    public static final n aQ;
    public static final n aR;
    public static final n aS;
    public static final n aT;
    public static final n aU;
    public static final n aV;
    public static final n aW;
    public static final n aa;
    public static final n ab;
    public static final n ac;
    public static final n ad;
    public static final n ae;
    public static final n af;
    public static final n ag;
    public static final n ah;
    public static final n ai;
    public static final n aj;
    public static final n ak;
    public static final n al;
    public static final n am;
    public static final n an;
    public static final n ao;
    public static final n ap;
    public static final n aq;
    public static final n ar;
    public static final n as;
    public static final n at;
    public static final n au;
    public static final n av;
    public static final n aw;
    public static final n ax;
    public static final n ay;
    public static final n az;

    static {
        int i = n.b;
        CM = new n(21851);
        CN = new n(21850);
        CO = new n(21849);
        CP = new n(9966);
        CQ = new n(27617);
        CR = new n(130702);
        CS = new n(27268);
        CT = new n(27618);
        CU = new n(26561);
        CV = new n(220059);
        CX = new n(47289);
        CY = new n(47294);
        CZ = new n(47296);
        Da = new n(20599);
        Db = new n(20600);
        Dc = new n(20601);
        Dd = new n(47290);
        De = new n(47291);
        Df = new n(47303);
        Dg = new n(88955);
        Dh = new n(88957);
        Di = new n(167292);
        Dj = new n(167286);
        Dk = new n(167291);
        Dl = new n(167289);
        Dm = new n(167288);
        Dn = new n(167293);
        Do = new n(167287);
        E = new n(167290);
        F = new n(167294);
        G = new n(47306);
        H = new n(47307);
        I = new n(47308);
        J = new n(47309);
        K = new n(47310);
        L = new n(47311);
        M = new n(47312);
        N = new n(47313);
        O = new n(47314);
        P = new n(47315);
        Q = new n(88956);
        R = new n(88958);
        S = new n(47316);
        T = new n(47317);
        U = new n(47318);
        V = new n(47339);
        W = new n(47319);
        X = new n(47322);
        Y = new n(47323);
        Z = new n(80244);
        aa = new n(80245);
        ab = new n(47324);
        ac = new n(47325);
        ad = new n(47326);
        ae = new n(133081);
        af = new n(77447);
        ag = new n(108656);
        ah = new n(47288);
        ai = new n(47273);
        aj = new n(47281);
        ak = new n(47272);
        al = new n(47283);
        am = new n(47285);
        an = new n(47284);
        ao = new n(47287);
        ap = new n(47286);
        aq = new n(47282);
        ar = new n(47275);
        as = new n(108657);
        at = new n(47278);
        au = new n(47276);
        av = new n(47277);
        aw = new n(20603);
        ax = new n(113449);
        ay = new n(47280);
        az = new n(47279);
        aA = new n(20602);
        aB = new n(123838);
        aC = new n(195290);
        aD = new n(101962);
        aE = new n(113448);
        aF = new n(47271);
        aG = new n(47274);
        aH = new n(46824);
        aI = new n(47292);
        aJ = new n(47293);
        aK = new n(47327);
        aL = new n(47328);
        aM = new n(47329);
        aN = new n(47330);
        aO = new n(47331);
        aP = new n(47332);
        aQ = new n(47333);
        aR = new n(47334);
        aS = new n(47336);
        aT = new n(37384);
        aU = new n(ExifDirectoryBase.TAG_METERING_MODE);
        aV = new n(9747);
        aW = new n(46458);
    }
}
