package com.google.android.libraries.navigation.internal.em;

import com.google.android.libraries.navigation.R;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes7.dex */
public final class a {
    public static final int A;
    public static final int B;
    public static final int C;
    public static final int D;
    public static final int E;
    public static final int F;
    public static final int G;
    public static final int H;
    public static final int I;
    public static final int J;
    public static final int K;
    public static final int L;
    public static final int M;
    public static final int N;
    public static final int O;
    public static final int P;
    public static final int Q;
    public static final int R;
    public static final int S;
    public static final int T;
    public static final int U;
    public static final int V;
    public static final int W;
    public static final int X;
    public static final int Y;
    public static final int Z;
    public static final int a;
    public static final int aA;
    public static final int aB;
    public static final int aC;
    public static final int aD;
    public static final int aE;
    public static final int aF;
    public static final int aG;
    public static final int aH;
    public static final int aI;
    public static final int aJ;
    public static final int aa;
    public static final int ab;
    public static final int ac;
    public static final int ad;
    public static final int ae;
    public static final int af;
    public static final int ag;
    public static final int ah;
    public static final int ai;
    public static final int aj;
    public static final int ak;
    public static final int al;
    public static final int am;
    public static final int an;
    public static final int ao;
    public static final int ap;
    public static final int aq;
    public static final int ar;
    public static final int as;
    public static final int at;
    public static final int au;
    public static final int av;
    public static final int aw;
    public static final int ax;
    public static final int ay;
    public static final int az;
    public static final int b;
    public static final int c;
    public static final int d;
    public static final int e;
    public static final int f;
    public static final int g;
    public static final int h;
    public static final int i;
    public static final int j;
    public static final int k;
    public static final int l;
    public static final int m;

    /* JADX INFO: renamed from: n, reason: collision with root package name */
    public static final int f423n;
    public static final int o;
    public static final int p;
    public static final int q;
    public static final int r;
    public static final int s;
    public static final int t;
    public static final int u;
    public static final int v;
    public static final int w;
    public static final int x;
    public static final int y;
    public static final int z;

    static {
        int i2 = R.string.ABOUT;
        a = R.string.ACCOUNT_SETTINGS_NOTIFICATION_SETTING_SUMMARY;
        b = R.string.ACCOUNT_SETTINGS_NOTIFICATION_SETTING_TITLE;
        c = R.string.BASE_LOCAL_DISCOVERY_NOTIFICATION_OPT_OUT_SETTINGS_SUMMARY;
        d = R.string.BASE_LOCAL_DISCOVERY_NOTIFICATION_SETTINGS_SUMMARY;
        e = R.string.BASE_LOCAL_DISCOVERY_NOTIFICATION_SETTINGS_TITLE;
        f = R.string.BUSINESS_MESSAGE_NOTIFICATION_OPT_OUT_SETTINGS_SUMMARY;
        g = R.string.BUSINESS_MESSAGE_NOTIFICATION_SETTINGS_SUMMARY;
        h = R.string.BUSINESS_MESSAGE_NOTIFICATION_SETTINGS_TITLE;
        i = R.string.COLLABORATIVE_LISTS_NOTIFICATION_OPT_OUT_SETTINGS_SUMMARY;
        j = R.string.COLLABORATIVE_LISTS_NOTIFICATION_SETTINGS_SUMMARY;
        k = R.string.COLLABORATIVE_LISTS_NOTIFICATION_SETTINGS_TITLE;
        l = R.string.COMMUTE_PROFILE_OPT_OUT_SETTINGS_SUMMARY;
        m = R.string.COMMUTE_PROFILE_SETTINGS_SUMMARY;
        f423n = R.string.COMMUTE_PROFILE_SETTINGS_TITLE;
        o = R.string.DEBUG_MAPS_FEATURES_SETTINGS_TITLE;
        p = R.string.GETTING_AROUND_CATEGORY_TITLE;
        q = R.string.GOOGLE_MAPS_TIMELINE_OPT_OUT_SETTINGS_SUMMARY;
        r = R.string.GOOGLE_MAPS_TIMELINE_SETTINGS_SUMMARY;
        s = R.string.GOOGLE_MAPS_TIMELINE_SETTINGS_TITLE;
        t = R.string.HOME_WORK_SETTINGS_SUMMARY;
        u = R.string.HOME_WORK_SETTINGS_TITLE;
        v = R.string.LOCATION_AND_PROFILE_CATEGORY_TITLE;
        w = R.string.LOCATION_SHARING_FRIENDS_OPT_OUT_SETTINGS_SUMMARY;
        x = R.string.LOCATION_SHARING_FRIENDS_SETTINGS_SUMMARY;
        y = R.string.LOCATION_SHARING_FRIENDS_SETTINGS_TITLE;
        z = R.string.LOCATION_SHARING_UPDATES_SETTINGS_SUMMARY;
        A = R.string.LOCATION_SHARING_UPDATES_SETTINGS_TITLE;
        B = R.string.LOCATION_SHARING_YOU_OPT_OUT_SETTINGS_SUMMARY;
        C = R.string.LOCATION_SHARING_YOU_SETTINGS_SUMMARY;
        D = R.string.LOCATION_SHARING_YOU_SETTINGS_TITLE;
        E = R.string.MAPS_FEATURES_CATEGORY_TITLE;
        F = R.string.MAPS_FEATURES_URGENT_SETTINGS_TITLE;
        G = R.string.NAVIGATION_CATEGORY_TITLE;
        H = R.string.NAVIGATION_URGENT_SETTINGS_TITLE;
        I = R.string.NEARBY_PLACES_NOTIFICATION_OPT_OUT_SETTINGS_SUMMARY_V2;
        J = R.string.NEARBY_PLACES_NOTIFICATION_SETTINGS_SUMMARY;
        K = R.string.NEARBY_PLACES_NOTIFICATION_SETTINGS_SUMMARY_V2;
        L = R.string.NEARBY_PLACES_NOTIFICATION_SETTINGS_TITLE;
        M = R.string.NEW_ON_MAPS_CATEGORY_TITLE;
        N = R.string.NEW_ON_MAPS_NOTIFICATION_OPT_OUT_SETTINGS_SUMMARY;
        O = R.string.NEW_ON_MAPS_NOTIFICATION_SETTINGS_SUMMARY;
        P = R.string.OFFLINE_MAPS_DOWNLOAD_EMBEDDED_TITLE;
        Q = R.string.OFFLINE_MAPS_NOTIFICATION_OPT_OUT_SETTINGS_SUMMARY;
        R = R.string.OFFLINE_MAPS_NOTIFICATION_SETTINGS_SUMMARY;
        S = R.string.OFFLINE_MAPS_TITLE;
        T = R.string.OTHER_NOTIFICATION_CHANNEL;
        U = R.string.PARKING_LOCATION_OPT_OUT_SETTINGS_SUMMARY;
        V = R.string.PARKING_LOCATION_SETTINGS_SUMMARY;
        W = R.string.PARKING_LOCATION_SETTINGS_TITLE;
        X = R.string.PHOTO_NOTIFICATION_OPT_OUT_SETTINGS_SUMMARY;
        Y = R.string.PHOTO_NOTIFICATION_SETTINGS_SUMMARY;
        Z = R.string.PHOTO_NOTIFICATION_SETTINGS_TITLE;
        aa = R.string.PICKUP_ORDERS_NOTIFICATION_OPT_OUT_SETTING_SUMMARY;
        ab = R.string.PICKUP_ORDERS_NOTIFICATION_SETTING_SUMMARY;
        ac = R.string.PICKUP_ORDERS_NOTIFICATION_SETTING_TITLE;
        ad = R.string.PLACES_NOTIFICATION_OPT_OUT_SETTINGS_SUMMARY;
        ae = R.string.PLACES_NOTIFICATION_SETTINGS_SUMMARY;
        af = R.string.PLACES_NOTIFICATION_SETTINGS_TITLE;
        ag = R.string.QA_AND_CHAT_CATEGORY_TITLE;
        ah = R.string.RECOMMENDATIONS_FOR_YOU_CATEGORY_TITLE;
        ai = R.string.REVIEWS_AND_MEDIA_CATEGORY_TITLE;
        aj = R.string.REVIEW_NOTIFICATION_OPT_OUT_SETTINGS_SUMMARY;
        ak = R.string.REVIEW_NOTIFICATION_SETTINGS_SUMMARY;
        al = R.string.REVIEW_NOTIFICATION_SETTINGS_TITLE;
        am = R.string.TIME_TO_LEAVE_OPT_OUT_SETTINGS_SUMMARY;
        an = R.string.TIME_TO_LEAVE_SETTINGS_SUMMARY;
        ao = R.string.TIME_TO_LEAVE_SETTINGS_TITLE;
        ap = R.string.TRAFFIC_IN_YOUR_AREA_OPT_OUT_SETTINGS_SUMMARY;
        aq = R.string.TRAFFIC_IN_YOUR_AREA_SETTINGS_SUMMARY;
        ar = R.string.TRAFFIC_IN_YOUR_AREA_SETTINGS_TITLE;
        as = R.string.TRAFFIC_NEARBY_EVENTS_OPT_OUT_SETTINGS_SUMMARY;
        at = R.string.TRAFFIC_NEARBY_EVENTS_SETTINGS_SUMMARY;
        au = R.string.TRAFFIC_NEARBY_EVENTS_SETTINGS_TITLE;
        av = R.string.TRANSIT_INFO_OPT_OUT_SETTINGS_SUMMARY;
        aw = R.string.TRANSIT_INFO_SETTINGS_SUMMARY;
        ax = R.string.TRANSIT_INFO_SETTINGS_TITLE;
        ay = R.string.UGC_IMPACT_NOTIFICATION_OPT_OUT_SETTINGS_SUMMARY;
        az = R.string.UGC_IMPACT_NOTIFICATION_SETTINGS_SUMMARY;
        aA = R.string.UGC_IMPACT_NOTIFICATION_SETTINGS_TITLE;
        aB = R.string.UGC_NOTIFICATION_OPT_OUT_SETTINGS_SUMMARY;
        aC = R.string.UGC_NOTIFICATION_SETTINGS_SUMMARY;
        aD = R.string.UGC_NOTIFICATION_SETTINGS_TITLE;
        aE = R.string.YOUR_BUSINESS_CATEGORY_TITLE;
        aF = R.string.YOUR_BUSINESS_OPT_OUT_SETTINGS_SUMMARY;
        aG = R.string.YOUR_BUSINESS_SETTINGS_SUMMARY;
        aH = R.string.YOUR_PROFILE_AND_FOLLOWING_NOTIFICATION_OPT_OUT_SETTING_SUMMARY;
        aI = R.string.YOUR_PROFILE_AND_FOLLOWING_NOTIFICATION_SETTING_SUMMARY;
        aJ = R.string.YOUR_PROFILE_AND_FOLLOWING_NOTIFICATION_SETTING_TITLE;
    }
}
