package com.google.android.libraries.navigation.internal.du;

import com.google.android.libraries.navigation.R;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes7.dex */
public final class c {
    public static final int A;
    public static final int B;
    public static final int C;
    public static final int D;
    public static final int E;
    public static final int F;
    public static final int G;
    public static final int H;
    public static final int I;
    public static final int J;
    public static final int K;
    public static final int L;
    public static final int M;
    public static final int N;
    public static final int O;
    public static final int P;
    public static final int Q;
    public static final int R;
    public static final int S;
    public static final int T;
    public static final int U;
    public static final int V;
    public static final int W;
    public static final int X;
    public static final int Y;
    public static final int Z;
    public static final int a;
    public static final int aA;
    public static final int aB;
    public static final int aa;
    public static final int ab;
    public static final int ac;
    public static final int ad;
    public static final int ae;
    public static final int af;
    public static final int ag;
    public static final int ah;
    public static final int ai;
    public static final int aj;
    public static final int ak;
    public static final int al;
    public static final int am;
    public static final int an;
    public static final int ao;
    public static final int ap;
    public static final int aq;
    public static final int ar;
    public static final int as;
    public static final int at;
    public static final int au;
    public static final int av;
    public static final int aw;
    public static final int ax;
    public static final int ay;
    public static final int az;
    public static final int b;
    public static final int c;
    public static final int d;
    public static final int e;
    public static final int f;
    public static final int g;
    public static final int h;
    public static final int i;
    public static final int j;
    public static final int k;
    public static final int l;
    public static final int m;

    /* JADX INFO: renamed from: n, reason: collision with root package name */
    public static final int f414n;
    public static final int o;
    public static final int p;
    public static final int q;
    public static final int r;
    public static final int s;
    public static final int t;
    public static final int u;
    public static final int v;
    public static final int w;
    public static final int x;
    public static final int y;
    public static final int z;

    static {
        int i2 = R.drawable.abc_ab_share_pack_mtrl_alpha;
        a = R.drawable.bearingless_gpslost_navigation_chevron;
        b = R.drawable.bearingless_navigation_chevron;
        c = R.drawable.bearingless_navigation_chevron_map_colors2;
        d = R.drawable.bearingless_navigation_chevron_night;
        e = R.drawable.bearingless_navigation_chevron_night_map_colors2;
        f = R.drawable.biking_blue_dot;
        g = R.drawable.biking_grey_dot;
        h = R.drawable.blue_arrow;
        i = R.drawable.blue_arrow_map_colors2;
        j = R.drawable.blue_cone_120;
        k = R.drawable.blue_cone_120_map_colors2;
        l = R.drawable.blue_cone_120_satellite;
        m = R.drawable.blue_cone_120_satellite_map_colors2;
        f414n = R.drawable.blue_cone_150;
        o = R.drawable.blue_cone_150_map_colors2;
        p = R.drawable.blue_cone_150_satellite;
        q = R.drawable.blue_cone_150_satellite_map_colors2;
        r = R.drawable.blue_cone_60;
        s = R.drawable.blue_cone_60_map_colors2;
        t = R.drawable.blue_cone_60_satellite;
        u = R.drawable.blue_cone_60_satellite_map_colors2;
        v = R.drawable.blue_cone_90;
        w = R.drawable.blue_cone_90_map_colors2;
        x = R.drawable.blue_cone_90_satellite;
        y = R.drawable.blue_cone_90_satellite_map_colors2;
        z = R.drawable.blue_dot_pulsate;
        A = R.drawable.blue_dot_pulsate_map_colors2;
        B = R.drawable.button_compass_night_selector;
        C = R.drawable.button_compass_selector;
        D = R.drawable.chevron_ghost_navigation_chevron_night;
        E = R.drawable.chevron_gpslost_night_disc;
        F = R.drawable.chevron_navigation_chevron;
        G = R.drawable.chevron_navigation_chevron_map_colors2;
        H = R.drawable.chevron_navigation_chevron_night;
        I = R.drawable.chevron_navigation_chevron_night_map_colors2;
        J = R.drawable.chevron_navigation_disc;
        K = R.drawable.chevron_navigation_disc_night;
        L = R.drawable.chevron_navigation_disc_night_map_colors2;
        M = R.drawable.drive_blue_dot;
        N = R.drawable.drive_grey_dot;
        O = R.drawable.drive_red_dot;
        P = R.drawable.incognito_arrow;
        Q = R.drawable.incognito_cone_120;
        R = R.drawable.incognito_cone_120_satellite;
        S = R.drawable.incognito_cone_150;
        T = R.drawable.incognito_cone_150_satellite;
        U = R.drawable.incognito_cone_60;
        V = R.drawable.incognito_cone_60_satellite;
        W = R.drawable.incognito_cone_90;
        X = R.drawable.incognito_cone_90_satellite;
        Y = R.drawable.incognito_dot;
        Z = R.drawable.incognito_dot_glow;
        aa = R.drawable.lite_nav_chevron;
        ab = R.drawable.lite_nav_glow;
        ac = R.drawable.lite_nav_gray_chevron;
        ad = R.drawable.new_blue_dot;
        ae = R.drawable.new_blue_dot_glow;
        af = R.drawable.new_blue_dot_glow_map_colors2;
        ag = R.drawable.new_direction_pointer;
        ah = R.drawable.new_gray_dot;
        ai = R.drawable.new_lite_nav_chevron;
        aj = R.drawable.new_lite_nav_glow;
        ak = R.drawable.quantum_ic_check_circle_blank_white_24;
        al = R.drawable.quantum_ic_gps_not_fixed_grey600_18;
        am = R.drawable.taxi_blue_dot;
        an = R.drawable.taxi_grey_dot;
        ao = R.drawable.travel_mode_blue_arrow;
        ap = R.drawable.travel_mode_blue_cone_120;
        aq = R.drawable.travel_mode_blue_cone_120_satellite;
        ar = R.drawable.travel_mode_blue_cone_150;
        as = R.drawable.travel_mode_blue_cone_150_satellite;
        at = R.drawable.travel_mode_blue_cone_60;
        au = R.drawable.travel_mode_blue_cone_60_satellite;
        av = R.drawable.travel_mode_blue_cone_90;
        aw = R.drawable.travel_mode_blue_cone_90_satellite;
        ax = R.drawable.two_wheeler_blue_dot;
        ay = R.drawable.two_wheeler_grey_dot;
        az = R.drawable.walking_blue_dot;
        aA = R.drawable.walking_grey_dot;
        aB = R.drawable.white_dot;
    }
}
