package com.google.android.libraries.navigation.internal.ee;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes7.dex */
public enum t {
    ANNOUNCEMENTS(com.google.android.libraries.navigation.internal.adu.m.ANNOUNCEMENTS, 116409198),
    AT_A_PLACE_LOCATION_HISTORY_GRANULAR_CONTROL(null, 166168806),
    BUSINESS_INSIGHTS(com.google.android.libraries.navigation.internal.adu.m.INSIGHTS_BUSINESS_NOTIFICATION, 251263586),
    BUSINESS_LISTINGS(com.google.android.libraries.navigation.internal.adu.m.BUSINESS_LISTINGS, 137767049),
    BUSINESS_OWNER_HOURS(com.google.android.libraries.navigation.internal.adu.m.BUSINESS_OWNER_HOURS, 155530005),
    BUSINESS_MERCHANT_MISSED_CALLS(com.google.android.libraries.navigation.internal.adu.m.MERCHANT_MISSED_CALLS, 366136506),
    BUSINESS_MESSAGING_MERCHANT_UNRESPONSIVE_SUMMARY(com.google.android.libraries.navigation.internal.adu.m.BUSINESS_MESSAGING_MERCHANT_UNRESPONSIVE_SUMMARY, 327866874),
    CHIME_BASIC_NOTIFICATION(null, 160185036),
    COMMUTE_NOTIFICATION_MINIMAP_UPDATE(null, 210428981),
    CONTRIBUTION_IMPACT_MILESTONE(com.google.android.libraries.navigation.internal.adu.m.CONTRIBUTION_IMPACT_MILESTONE, 194198581),
    COMMUTE_WARMUP_HOME_ONLY(null, 191700883),
    DESKTOP_CALL(com.google.android.libraries.navigation.internal.adu.m.DESKTOP_CALL, 248423582),
    EDIT_PUBLISHED(com.google.android.libraries.navigation.internal.adu.m.EDIT_PUBLISHED, 105849280),
    EMPLOYEE_HOURS(com.google.android.libraries.navigation.internal.adu.m.EMPLOYEE_HOURS, 127850489),
    FOOD_REMINDER(com.google.android.libraries.navigation.internal.adu.m.FOOD_REMINDER, 280328122),
    GENERIC_NOTIFICATION(null, 114233125),
    GUNS_LIGHT_TICKLE_HANDLING(null, 185929514),
    IN_APP_SHARE(com.google.android.libraries.navigation.internal.adu.m.IN_APP_SHARE, 207917237),
    INFERRED_COMMUTE_LOCATION_WARMUP_BANNER(null, 177079802),
    JOURNEY_SHARING_ARRIVAL_NOTIFICATION(com.google.android.libraries.navigation.internal.adu.m.JOURNEY_SHARING_ARRIVAL_NOTIFICATION_RECEIVED, 224926800),
    LOCAL_DISCOVERY_AT_A_PLACE(com.google.android.libraries.navigation.internal.adu.m.LOCAL_DISCOVERY_AT_A_PLACE, 257161995),
    LOCAL_DISCOVERY_NEW_POST(com.google.android.libraries.navigation.internal.adu.m.LOCAL_DISCOVERY_NEW_POST, 215229809),
    LOCAL_DISCOVERY_WELCOME_TO_DESTINATION(com.google.android.libraries.navigation.internal.adu.m.LOCAL_DISCOVERY_WELCOME_TO_DESTINATION, 254137460),
    LOCAL_EVENT(com.google.android.libraries.navigation.internal.adu.m.LOCAL_EVENT, 98516671),
    LOCAL_GUIDES_PERKS(com.google.android.libraries.navigation.internal.adu.m.LOCAL_GUIDES_PERKS, 179523605),
    LOCATION_SHARE(com.google.android.libraries.navigation.internal.adu.m.SHARED_LOCATION_RECEIVED, 128314788),
    LOCATION_SHARING_REQUEST(com.google.android.libraries.navigation.internal.adu.m.SHARED_LOCATION_REQUEST, 150586414),
    MAPS_BADGES(com.google.android.libraries.navigation.internal.adu.m.MAPS_BADGES, 155595117),
    NEW_BUSINESS_REVIEW(com.google.android.libraries.navigation.internal.adu.m.NEW_BUSINESS_REVIEW, 228514107),
    OVEN_FRESH(null, 218597578),
    PEOPLE_FOLLOW_NEW_FOLLOWER(com.google.android.libraries.navigation.internal.adu.m.PEOPLE_FOLLOW_NEW_FOLLOWER, 295825709),
    PEOPLE_FOLLOW_NEW_REQUEST(com.google.android.libraries.navigation.internal.adu.m.PEOPLE_FOLLOW_NEW_REQUEST, 295825712),
    PHOTO_TAKEN(com.google.android.libraries.navigation.internal.adu.m.PHOTO_TAKEN, 150146463),
    SERVER_PHOTO_TAKEN_NOTIFICATION_SOMEWHERE_ELSE_ACTION(null, 266693778),
    PHOTO_UPDATE(null, 338374842),
    PLACE_LIST_JOINED(com.google.android.libraries.navigation.internal.adu.m.PLACE_LIST_JOINED, 252824331),
    PLACE_QA_MERCHANT(com.google.android.libraries.navigation.internal.adu.m.PLACE_QA_MERCHANT, 158047068),
    PLACE_QA(com.google.android.libraries.navigation.internal.adu.m.PLACE_QA, 154121765),
    POI_WIZARD(com.google.android.libraries.navigation.internal.adu.m.UGC_AT_A_PLACE_POI_WIZARD_NOTIFICATION, 374355822),
    POST_CONTRIBUTION_IMPACT(com.google.android.libraries.navigation.internal.adu.m.POST_CONTRIBUTION_IMPACT, 173993735),
    POST_PHOTO_VIEWS(com.google.android.libraries.navigation.internal.adu.m.POST_PHOTO_VIEWS, 184800990),
    REENGAGEMENT_CATEGORICAL_SEARCH_REOPENED_BUSINESS(com.google.android.libraries.navigation.internal.adu.m.REENGAGEMENT_CATEGORICAL_SEARCH_REOPENED_BUSINESS, 314766071),
    REENGAGEMENT_CATEGORICAL_SEARCH_TAKEOUT(com.google.android.libraries.navigation.internal.adu.m.REENGAGEMENT_CATEGORICAL_SEARCH_TAKEOUT, 314233277),
    REENGAGEMENT_PLACESHEET_REOPENED_BUSINESS(com.google.android.libraries.navigation.internal.adu.m.REENGAGEMENT_PLACESHEET_REOPENED_BUSINESS, 314767184),
    REENGAGEMENT_PLACESHEET_TAKEOUT(com.google.android.libraries.navigation.internal.adu.m.REENGAGEMENT_PLACESHEET_TAKEOUT, 314353463),
    REVIEW_AT_A_PLACE(com.google.android.libraries.navigation.internal.adu.m.REVIEW_AT_A_PLACE, 156960199),
    REVIEW_AT_A_PLACE_NOTIFICATION_DIDNT_GO_HERE_ACTION(null, 323310702),
    REVIEW_UPDATE(null, 398656074),
    RIDDLER_NOTIFICATION_DIDNT_GO_HERE_ACTION(null, 360571991),
    REVIEW_REPLY(com.google.android.libraries.navigation.internal.adu.m.REVIEW_REPLY, 217516401),
    RIDDLER(com.google.android.libraries.navigation.internal.adu.m.RIDDLER, 207485373),
    SAVE_OFFLINE_MAP(null, 130134837),
    SEND_TO_PHONE(com.google.android.libraries.navigation.internal.adu.m.SEND_TO_PHONE, 71471187),
    SET_ALIAS(com.google.android.libraries.navigation.internal.adu.m.SET_ALIAS, 150080536),
    SMARTSPACE_CHIME(null, 161539092),
    SOCIAL_PLANNING_PLACE_ADDED(com.google.android.libraries.navigation.internal.adu.m.SOCIAL_PLANNING_PLACE_ADDED, 195666667),
    SOCIAL_PLANNING_PLACE_REACTION(com.google.android.libraries.navigation.internal.adu.m.SOCIAL_PLANNING_PLACE_REACTION, 198093372),
    TIME_TO_LEAVE(com.google.android.libraries.navigation.internal.adu.m.TIME_TO_LEAVE, 198594557),
    TIMELINE_RECEIPTS_PARSED(com.google.android.libraries.navigation.internal.adu.m.TIMELINE_RECEIPTS_PARSED, 253993429),
    TIMELINE_VISIT_CONFIRMATION(com.google.android.libraries.navigation.internal.adu.m.TIMELINE_VISIT_CONFIRMATION, 105884846),
    TIMELINE_WARM_WELCOME(com.google.android.libraries.navigation.internal.adu.m.TIMELINE_WARM_WELCOME, 164117594),
    TODO_LIST(com.google.android.libraries.navigation.internal.adu.m.TODO_LIST, 119604319),
    TODO_NOTIFICATIONS_DIDNT_GO_HERE_ACTION(null, 400878825),
    TODO_PHOTO(com.google.android.libraries.navigation.internal.adu.m.TODO_PHOTO, 270848172),
    TODO_REVIEW(com.google.android.libraries.navigation.internal.adu.m.TODO_REVIEW, 126275446),
    TRAFFIC_TO_PLACE(com.google.android.libraries.navigation.internal.adu.m.TRAFFIC_TO_PLACE, 127259611),
    UGC_FACTUAL_EDIT_SURVEY(null, 437907875),
    UGC_FACTUAL_IMPACT_ADD_A_PLACE(com.google.android.libraries.navigation.internal.adu.m.UGC_FACTUAL_IMPACT_ADD_A_PLACE, 264991908),
    UGC_FACTUAL_IMPACT_LOCATION_EDIT(com.google.android.libraries.navigation.internal.adu.m.UGC_FACTUAL_IMPACT_LOCATION_EDIT, 264993433),
    UGC_HOME_STREET(com.google.android.libraries.navigation.internal.adu.m.UGC_HOME_STREET, 176052143),
    UGC_LOCATION_HISTORY_RECONSENT_OPEN_CT_ACTION(null, 466265427),
    UGC_PHOTO_BECAME_PLACE_HERO_IMAGE(com.google.android.libraries.navigation.internal.adu.m.UGC_PHOTO_BECAME_PLACE_HERO_IMAGE, 209353811),
    UGC_POST_TRIP_QUESTIONS(com.google.android.libraries.navigation.internal.adu.m.UGC_POST_TRIP_QUESTIONS, 160917170);

    public final int av;
    public final com.google.android.libraries.navigation.internal.adu.m aw;

    t(com.google.android.libraries.navigation.internal.adu.m mVar, int i) {
        this.av = i;
        this.aw = mVar;
    }
}
