package com.google.android.libraries.navigation.internal.pu;

import android.content.Context;
import android.content.res.Resources;
import com.google.android.libraries.geo.mapcore.internal.model.ct;
import com.google.android.libraries.navigation.internal.po.gm;
import com.google.android.libraries.navigation.internal.po.gr;
import com.google.android.libraries.navigation.internal.qu.cf;
import com.google.android.libraries.navigation.internal.yx.br;
import java.util.concurrent.Executor;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes7.dex */
public final class af implements com.google.android.libraries.navigation.internal.afr.f {
    private final com.google.android.libraries.navigation.internal.agl.a A;
    private final com.google.android.libraries.navigation.internal.agl.a B;
    private final com.google.android.libraries.navigation.internal.agl.a C;
    private final com.google.android.libraries.navigation.internal.agl.a D;
    private final com.google.android.libraries.navigation.internal.agl.a E;
    private final com.google.android.libraries.navigation.internal.agl.a F;
    private final com.google.android.libraries.navigation.internal.agl.a G;
    private final com.google.android.libraries.navigation.internal.agl.a H;
    private final com.google.android.libraries.navigation.internal.agl.a I;
    private final com.google.android.libraries.navigation.internal.agl.a J;
    private final com.google.android.libraries.navigation.internal.agl.a K;
    private final com.google.android.libraries.navigation.internal.agl.a L;
    private final com.google.android.libraries.navigation.internal.agl.a M;
    private final com.google.android.libraries.navigation.internal.agl.a N;
    private final com.google.android.libraries.navigation.internal.agl.a O;
    private final com.google.android.libraries.navigation.internal.agl.a P;
    private final com.google.android.libraries.navigation.internal.agl.a Q;
    private final com.google.android.libraries.navigation.internal.agl.a R;
    private final com.google.android.libraries.navigation.internal.agl.a S;
    private final com.google.android.libraries.navigation.internal.agl.a T;
    private final com.google.android.libraries.navigation.internal.agl.a U;
    private final com.google.android.libraries.navigation.internal.agl.a V;
    private final com.google.android.libraries.navigation.internal.agl.a W;
    private final com.google.android.libraries.navigation.internal.agl.a X;
    private final com.google.android.libraries.navigation.internal.agl.a Y;
    private final com.google.android.libraries.navigation.internal.agl.a a;
    private final com.google.android.libraries.navigation.internal.agl.a b;
    private final com.google.android.libraries.navigation.internal.agl.a c;
    private final com.google.android.libraries.navigation.internal.agl.a d;
    private final com.google.android.libraries.navigation.internal.agl.a e;
    private final com.google.android.libraries.navigation.internal.agl.a f;
    private final com.google.android.libraries.navigation.internal.agl.a g;
    private final com.google.android.libraries.navigation.internal.agl.a h;
    private final com.google.android.libraries.navigation.internal.agl.a i;
    private final com.google.android.libraries.navigation.internal.agl.a j;
    private final com.google.android.libraries.navigation.internal.agl.a k;
    private final com.google.android.libraries.navigation.internal.agl.a l;
    private final com.google.android.libraries.navigation.internal.agl.a m;

    /* JADX INFO: renamed from: n, reason: collision with root package name */
    private final com.google.android.libraries.navigation.internal.agl.a f531n;
    private final com.google.android.libraries.navigation.internal.agl.a o;
    private final com.google.android.libraries.navigation.internal.agl.a p;
    private final com.google.android.libraries.navigation.internal.agl.a q;
    private final com.google.android.libraries.navigation.internal.agl.a r;
    private final com.google.android.libraries.navigation.internal.agl.a s;
    private final com.google.android.libraries.navigation.internal.agl.a t;
    private final com.google.android.libraries.navigation.internal.agl.a u;
    private final com.google.android.libraries.navigation.internal.agl.a v;
    private final com.google.android.libraries.navigation.internal.agl.a w;
    private final com.google.android.libraries.navigation.internal.agl.a x;
    private final com.google.android.libraries.navigation.internal.agl.a y;
    private final com.google.android.libraries.navigation.internal.agl.a z;

    public af(com.google.android.libraries.navigation.internal.agl.a aVar, com.google.android.libraries.navigation.internal.agl.a aVar2, com.google.android.libraries.navigation.internal.agl.a aVar3, com.google.android.libraries.navigation.internal.agl.a aVar4, com.google.android.libraries.navigation.internal.agl.a aVar5, com.google.android.libraries.navigation.internal.agl.a aVar6, com.google.android.libraries.navigation.internal.agl.a aVar7, com.google.android.libraries.navigation.internal.agl.a aVar8, com.google.android.libraries.navigation.internal.agl.a aVar9, com.google.android.libraries.navigation.internal.agl.a aVar10, com.google.android.libraries.navigation.internal.agl.a aVar11, com.google.android.libraries.navigation.internal.agl.a aVar12, com.google.android.libraries.navigation.internal.agl.a aVar13, com.google.android.libraries.navigation.internal.agl.a aVar14, com.google.android.libraries.navigation.internal.agl.a aVar15, com.google.android.libraries.navigation.internal.agl.a aVar16, com.google.android.libraries.navigation.internal.agl.a aVar17, com.google.android.libraries.navigation.internal.agl.a aVar18, com.google.android.libraries.navigation.internal.agl.a aVar19, com.google.android.libraries.navigation.internal.agl.a aVar20, com.google.android.libraries.navigation.internal.agl.a aVar21, com.google.android.libraries.navigation.internal.agl.a aVar22, com.google.android.libraries.navigation.internal.agl.a aVar23, com.google.android.libraries.navigation.internal.agl.a aVar24, com.google.android.libraries.navigation.internal.agl.a aVar25, com.google.android.libraries.navigation.internal.agl.a aVar26, com.google.android.libraries.navigation.internal.agl.a aVar27, com.google.android.libraries.navigation.internal.agl.a aVar28, com.google.android.libraries.navigation.internal.agl.a aVar29, com.google.android.libraries.navigation.internal.agl.a aVar30, com.google.android.libraries.navigation.internal.agl.a aVar31, com.google.android.libraries.navigation.internal.agl.a aVar32, com.google.android.libraries.navigation.internal.agl.a aVar33, com.google.android.libraries.navigation.internal.agl.a aVar34, com.google.android.libraries.navigation.internal.agl.a aVar35, com.google.android.libraries.navigation.internal.agl.a aVar36, com.google.android.libraries.navigation.internal.agl.a aVar37, com.google.android.libraries.navigation.internal.agl.a aVar38, com.google.android.libraries.navigation.internal.agl.a aVar39, com.google.android.libraries.navigation.internal.agl.a aVar40, com.google.android.libraries.navigation.internal.agl.a aVar41, com.google.android.libraries.navigation.internal.agl.a aVar42, com.google.android.libraries.navigation.internal.agl.a aVar43, com.google.android.libraries.navigation.internal.agl.a aVar44, com.google.android.libraries.navigation.internal.agl.a aVar45, com.google.android.libraries.navigation.internal.agl.a aVar46, com.google.android.libraries.navigation.internal.agl.a aVar47, com.google.android.libraries.navigation.internal.agl.a aVar48, com.google.android.libraries.navigation.internal.agl.a aVar49, com.google.android.libraries.navigation.internal.agl.a aVar50, com.google.android.libraries.navigation.internal.agl.a aVar51) {
        this.a = aVar;
        this.b = aVar2;
        this.c = aVar3;
        this.d = aVar4;
        this.e = aVar5;
        this.f = aVar6;
        this.g = aVar7;
        this.h = aVar8;
        this.i = aVar9;
        this.j = aVar10;
        this.k = aVar11;
        this.l = aVar12;
        this.m = aVar13;
        this.f531n = aVar14;
        this.o = aVar15;
        this.p = aVar16;
        this.q = aVar17;
        this.r = aVar18;
        this.s = aVar19;
        this.t = aVar20;
        this.u = aVar21;
        this.v = aVar22;
        this.w = aVar23;
        this.x = aVar24;
        this.y = aVar25;
        this.z = aVar26;
        this.A = aVar27;
        this.B = aVar28;
        this.C = aVar29;
        this.D = aVar30;
        this.E = aVar31;
        this.F = aVar32;
        this.G = aVar33;
        this.H = aVar34;
        this.I = aVar35;
        this.J = aVar36;
        this.K = aVar37;
        this.L = aVar38;
        this.M = aVar39;
        this.N = aVar40;
        this.O = aVar41;
        this.P = aVar42;
        this.Q = aVar43;
        this.R = aVar44;
        this.S = aVar45;
        this.T = aVar46;
        this.U = aVar47;
        this.V = aVar48;
        this.W = aVar49;
        this.X = aVar50;
        this.Y = aVar51;
    }

    @Override // com.google.android.libraries.navigation.internal.agl.a, com.google.android.libraries.navigation.internal.agk.a
    public final /* bridge */ /* synthetic */ Object a() {
        com.google.android.libraries.geo.mapcore.internal.model.x xVar = (com.google.android.libraries.geo.mapcore.internal.model.x) this.a.a();
        com.google.android.libraries.navigation.internal.ob.n nVar = (com.google.android.libraries.navigation.internal.ob.n) ((com.google.android.libraries.navigation.internal.afr.g) this.b).a;
        Context context = (Context) ((com.google.android.libraries.navigation.internal.afr.g) this.c).a;
        com.google.android.libraries.navigation.internal.pq.b bVar = (com.google.android.libraries.navigation.internal.pq.b) this.e.a();
        com.google.android.libraries.navigation.internal.afo.a aVarC = com.google.android.libraries.navigation.internal.afr.e.c(this.f);
        gr grVar = (gr) this.g.a();
        com.google.android.libraries.navigation.internal.afo.a aVarC2 = com.google.android.libraries.navigation.internal.afr.e.c(this.h);
        com.google.android.libraries.navigation.internal.afo.a aVarC3 = com.google.android.libraries.navigation.internal.afr.e.c(this.i);
        com.google.android.libraries.navigation.internal.qd.k kVar = (com.google.android.libraries.navigation.internal.qd.k) this.j.a();
        Context context2 = (Context) this.k.a();
        com.google.android.libraries.navigation.internal.fq.f fVar = (com.google.android.libraries.navigation.internal.fq.f) this.l.a();
        com.google.android.libraries.navigation.internal.kl.b bVar2 = (com.google.android.libraries.navigation.internal.kl.b) this.m.a();
        com.google.android.libraries.navigation.internal.om.p pVar = (com.google.android.libraries.navigation.internal.om.p) this.f531n.a();
        com.google.android.libraries.navigation.internal.ox.f fVar2 = (com.google.android.libraries.navigation.internal.ox.f) this.o.a();
        com.google.android.libraries.navigation.internal.pm.d dVar = (com.google.android.libraries.navigation.internal.pm.d) this.p.a();
        com.google.android.libraries.navigation.internal.mj.a aVar = (com.google.android.libraries.navigation.internal.mj.a) this.q.a();
        com.google.android.libraries.navigation.internal.hp.e eVar = (com.google.android.libraries.navigation.internal.hp.e) this.r.a();
        com.google.android.libraries.navigation.internal.ni.a aVar2 = (com.google.android.libraries.navigation.internal.ni.a) this.s.a();
        com.google.android.libraries.navigation.internal.pi.s sVar = (com.google.android.libraries.navigation.internal.pi.s) this.t.a();
        com.google.android.libraries.navigation.internal.ia.e eVar2 = (com.google.android.libraries.navigation.internal.ia.e) this.u.a();
        com.google.android.libraries.navigation.internal.kg.c cVar = (com.google.android.libraries.navigation.internal.kg.c) this.v.a();
        com.google.android.libraries.navigation.internal.qf.d dVar2 = (com.google.android.libraries.navigation.internal.qf.d) this.w.a();
        com.google.android.libraries.navigation.internal.iv.f fVar3 = (com.google.android.libraries.navigation.internal.iv.f) this.x.a();
        com.google.android.libraries.navigation.internal.di.b bVar3 = (com.google.android.libraries.navigation.internal.di.b) this.y.a();
        com.google.android.libraries.navigation.internal.qy.h hVar = (com.google.android.libraries.navigation.internal.qy.h) this.z.a();
        com.google.android.libraries.navigation.internal.pm.a aVar3 = (com.google.android.libraries.navigation.internal.pm.a) this.A.a();
        com.google.android.libraries.navigation.internal.ra.a aVar4 = (com.google.android.libraries.navigation.internal.ra.a) this.B.a();
        com.google.android.libraries.navigation.internal.iz.n nVar2 = (com.google.android.libraries.navigation.internal.iz.n) this.C.a();
        com.google.android.libraries.navigation.internal.aac.bn bnVarA = ((com.google.android.libraries.navigation.internal.nj.h) this.D).a();
        com.google.android.libraries.navigation.internal.aac.bn bnVarA2 = ((com.google.android.libraries.navigation.internal.nj.b) this.E).a();
        com.google.android.libraries.navigation.internal.aac.bn bnVarA3 = ((com.google.android.libraries.navigation.internal.hy.ac) this.F).a();
        Executor executorA = ((com.google.android.libraries.navigation.internal.hy.n) this.G).a();
        com.google.android.libraries.navigation.internal.aac.bn bnVarB = com.google.android.libraries.navigation.internal.hy.q.b();
        cf cfVar = (cf) this.I.a();
        com.google.android.libraries.navigation.internal.pg.g gVar = (com.google.android.libraries.navigation.internal.pg.g) this.J.a();
        com.google.android.libraries.navigation.internal.yx.an anVar = (com.google.android.libraries.navigation.internal.yx.an) ((com.google.android.libraries.navigation.internal.afr.g) this.K).a;
        com.google.android.libraries.navigation.internal.pn.l lVar = (com.google.android.libraries.navigation.internal.pn.l) this.L.a();
        ct ctVar = (ct) this.M.a();
        br brVar = (br) this.N.a();
        com.google.android.libraries.navigation.internal.ob.t tVar = (com.google.android.libraries.navigation.internal.ob.t) this.O.a();
        com.google.android.libraries.navigation.internal.qs.a aVar5 = (com.google.android.libraries.navigation.internal.qs.a) this.P.a();
        com.google.android.libraries.navigation.internal.rc.c cVar2 = (com.google.android.libraries.navigation.internal.rc.c) this.Q.a();
        com.google.android.libraries.navigation.internal.oe.at atVar = (com.google.android.libraries.navigation.internal.oe.at) this.R.a();
        com.google.android.libraries.navigation.internal.rg.b bVar4 = (com.google.android.libraries.navigation.internal.rg.b) this.S.a();
        k kVar2 = (k) this.T.a();
        boolean zBooleanValue = ((Boolean) ((com.google.android.libraries.navigation.internal.afr.g) this.U).a).booleanValue();
        com.google.android.libraries.navigation.internal.adi.an anVar2 = (com.google.android.libraries.navigation.internal.adi.an) ((com.google.android.libraries.navigation.internal.afr.g) this.V).a;
        com.google.android.libraries.navigation.internal.yx.an anVar3 = (com.google.android.libraries.navigation.internal.yx.an) ((com.google.android.libraries.navigation.internal.afr.g) this.W).a;
        com.google.android.libraries.navigation.internal.yx.an anVar4 = (com.google.android.libraries.navigation.internal.yx.an) ((com.google.android.libraries.navigation.internal.afr.g) this.X).a;
        com.google.android.libraries.navigation.internal.pn.g gVar2 = new com.google.android.libraries.navigation.internal.pn.g((com.google.android.libraries.navigation.internal.pn.j) anVar.f(), lVar);
        Resources resources = context.getResources();
        String str = (String) anVar3.e("");
        Integer num = (Integer) anVar4.f();
        com.google.android.libraries.navigation.internal.ps.y yVar = (com.google.android.libraries.navigation.internal.ps.y) bVar;
        pVar.b();
        pVar.b();
        resources.getClass();
        xVar.getClass();
        nVar.getClass();
        context.getClass();
        yVar.getClass();
        anVar2.getClass();
        aVarC.getClass();
        grVar.getClass();
        aVarC2.getClass();
        aVarC3.getClass();
        kVar.getClass();
        context2.getClass();
        fVar.getClass();
        bVar2.getClass();
        pVar.getClass();
        fVar2.getClass();
        dVar.getClass();
        aVar.getClass();
        eVar.getClass();
        aVar2.getClass();
        sVar.getClass();
        eVar2.getClass();
        cVar.getClass();
        dVar2.getClass();
        fVar3.getClass();
        bVar3.getClass();
        hVar.getClass();
        aVar3.getClass();
        aVar4.getClass();
        nVar2.getClass();
        cfVar.getClass();
        gVar.getClass();
        ctVar.getClass();
        brVar.getClass();
        aVar5.getClass();
        cVar2.getClass();
        atVar.getClass();
        return new gm(str, num, resources, xVar, nVar, context, yVar, anVar2, aVarC, grVar, aVarC2, aVarC3, kVar, context2, fVar, bVar2, pVar, fVar2, dVar, aVar, eVar, aVar2, sVar, eVar2, cVar, dVar2, fVar3, bVar3, hVar, aVar3, aVar4, nVar2, bnVarA, bnVarA2, bnVarA3, executorA, bnVarB, cfVar, gVar, ctVar, gVar2, brVar, tVar, aVar5, cVar2, atVar, bVar4, kVar2, zBooleanValue, false);
    }
}
