package com.google.android.libraries.navigation.internal.cq;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes7.dex */
public enum k {
    UNKNOWN,
    SEPARATE_BIKE_LANE,
    MARKED_BIKE_LANE,
    COMBINED_BIKE_LANE,
    STAIRS,
    HEAVY_TRAFFIC,
    HEIGHT_RESTRICTION,
    WIDTH_RESTRICTION,
    WEIGHT_RESTRICTION,
    LENGTH_RESTRICTION,
    HAZMAT_RESTRICTION,
    LOW_DATA_QUALITY_ZONE,
    TRUCKS_PROHIBITED_RESTRICTION,
    FLYOVER,
    UNPAVED_ROAD,
    ICY_ROAD,
    HOV,
    JAMCIDENT_ROAD_STRETCH_SLOWER_TRAFFIC,
    JAMCIDENT_ROAD_STRETCH_TRAFFIC_JAM,
    JAMCIDENT_VISUALIZATION_JAM_STRETCH,
    ETC_ONLY_TOLL_GATE,
    NARROW_ROAD
}
