package com.google.android.libraries.navigation.internal.abm;

import android.content.Context;
import com.google.android.libraries.navigation.internal.po.go;
import com.google.android.libraries.navigation.internal.po.gs;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes7.dex */
final class k implements com.google.android.libraries.navigation.internal.pu.b {
    private com.google.android.libraries.navigation.internal.afr.k A;
    private com.google.android.libraries.navigation.internal.afr.k B;
    private com.google.android.libraries.navigation.internal.afr.k C;
    private com.google.android.libraries.navigation.internal.afr.k D;
    private com.google.android.libraries.navigation.internal.afr.k E;
    private com.google.android.libraries.navigation.internal.afr.k F;
    private com.google.android.libraries.navigation.internal.afr.k G;
    private com.google.android.libraries.navigation.internal.afr.k H;
    private com.google.android.libraries.navigation.internal.afr.k I;
    private com.google.android.libraries.navigation.internal.afr.k J;
    private com.google.android.libraries.navigation.internal.afr.k K;
    private com.google.android.libraries.navigation.internal.afr.k L;
    private com.google.android.libraries.navigation.internal.afr.k M;
    private com.google.android.libraries.navigation.internal.afr.k N;
    private com.google.android.libraries.navigation.internal.afr.k O;
    private com.google.android.libraries.navigation.internal.afr.k P;
    private com.google.android.libraries.navigation.internal.afr.k Q;
    private com.google.android.libraries.navigation.internal.afr.k R;
    private com.google.android.libraries.navigation.internal.afr.k S;
    private com.google.android.libraries.navigation.internal.afr.k T;
    private com.google.android.libraries.navigation.internal.afr.k U;
    private com.google.android.libraries.navigation.internal.afr.k V;
    private com.google.android.libraries.navigation.internal.afr.k W;
    private com.google.android.libraries.navigation.internal.afr.k X;
    private com.google.android.libraries.navigation.internal.afr.k Y;
    private com.google.android.libraries.navigation.internal.afr.k Z;
    private final p a;
    private com.google.android.libraries.navigation.internal.afr.k aa;
    private com.google.android.libraries.navigation.internal.afr.k ab;
    private com.google.android.libraries.navigation.internal.afr.k ac;
    private com.google.android.libraries.navigation.internal.afr.k ad;
    private com.google.android.libraries.navigation.internal.afr.k ae;
    private com.google.android.libraries.navigation.internal.afr.k af;
    private com.google.android.libraries.navigation.internal.afr.k ag;
    private com.google.android.libraries.navigation.internal.afr.k ah;
    private com.google.android.libraries.navigation.internal.afr.k ai;
    private com.google.android.libraries.navigation.internal.afr.k aj;
    private com.google.android.libraries.navigation.internal.afr.k ak;
    private com.google.android.libraries.navigation.internal.afr.k al;
    private com.google.android.libraries.navigation.internal.afr.k am;
    private com.google.android.libraries.navigation.internal.afr.k b;
    private com.google.android.libraries.navigation.internal.afr.k c;
    private com.google.android.libraries.navigation.internal.afr.k d;
    private com.google.android.libraries.navigation.internal.afr.k e;
    private com.google.android.libraries.navigation.internal.afr.k f;
    private com.google.android.libraries.navigation.internal.afr.k g;
    private com.google.android.libraries.navigation.internal.afr.k h;
    private com.google.android.libraries.navigation.internal.afr.k i;
    private com.google.android.libraries.navigation.internal.afr.k j;
    private com.google.android.libraries.navigation.internal.afr.k k;
    private com.google.android.libraries.navigation.internal.afr.k l;
    private com.google.android.libraries.navigation.internal.afr.k m;

    /* JADX INFO: renamed from: n, reason: collision with root package name */
    private com.google.android.libraries.navigation.internal.afr.k f138n;
    private com.google.android.libraries.navigation.internal.afr.k o;
    private com.google.android.libraries.navigation.internal.afr.k p;
    private com.google.android.libraries.navigation.internal.afr.k q;
    private com.google.android.libraries.navigation.internal.afr.k r;
    private com.google.android.libraries.navigation.internal.afr.k s;
    private com.google.android.libraries.navigation.internal.afr.k t;
    private com.google.android.libraries.navigation.internal.afr.k u;
    private com.google.android.libraries.navigation.internal.afr.k v;
    private com.google.android.libraries.navigation.internal.afr.k w;
    private com.google.android.libraries.navigation.internal.afr.k x;
    private com.google.android.libraries.navigation.internal.afr.k y;
    private com.google.android.libraries.navigation.internal.afr.k z;

    public k(p pVar, Context context, com.google.android.libraries.navigation.internal.ob.n nVar, com.google.android.libraries.navigation.internal.pz.c cVar, com.google.android.libraries.navigation.internal.yx.an anVar, com.google.android.libraries.navigation.internal.yx.an anVar2, com.google.android.libraries.navigation.internal.yx.an anVar3, com.google.android.libraries.navigation.internal.yx.an anVar4, com.google.android.libraries.navigation.internal.yx.an anVar5, Boolean bool, com.google.android.libraries.navigation.internal.kn.a aVar, com.google.android.libraries.navigation.internal.adi.an anVar6, com.google.android.libraries.navigation.internal.yx.an anVar7, com.google.android.libraries.navigation.internal.yx.an anVar8, com.google.android.libraries.navigation.internal.ob.w wVar) {
        this.a = pVar;
        this.b = com.google.android.libraries.navigation.internal.afr.g.b(nVar);
        this.c = com.google.android.libraries.navigation.internal.afr.g.b(context);
        this.d = com.google.android.libraries.navigation.internal.afr.g.b(cVar);
        com.google.android.libraries.navigation.internal.ps.z zVar = new com.google.android.libraries.navigation.internal.ps.z(com.google.android.libraries.navigation.internal.ps.l.a);
        this.e = zVar;
        this.f = com.google.android.libraries.navigation.internal.afr.e.d(zVar);
        com.google.android.libraries.navigation.internal.afr.k kVarD = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.y(this.c, pVar.h, pVar.t, pVar.q, pVar.c));
        this.g = kVarD;
        gs gsVar = new gs(kVarD);
        this.h = gsVar;
        this.i = com.google.android.libraries.navigation.internal.afr.e.d(gsVar);
        this.j = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.z(pVar.k, pVar.L));
        this.k = new com.google.android.libraries.navigation.internal.qq.am(this.c, pVar.e, pVar.t, this.g, pVar.F, this.j, pVar.m, pVar.j, pVar.h, pVar.s, pVar.o, pVar.u);
        this.l = com.google.android.libraries.navigation.internal.afr.g.b(anVar5);
        com.google.android.libraries.navigation.internal.afr.f fVarB = com.google.android.libraries.navigation.internal.afr.g.b(anVar);
        this.m = fVarB;
        this.f138n = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.am(this.l, fVarB, pVar.p, pVar.e, pVar.N, pVar.g, pVar.r, pVar.f));
        this.o = com.google.android.libraries.navigation.internal.afr.g.b(aVar);
        this.p = v.a;
        this.q = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.as(pVar.h, this.o, this.p));
        this.r = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.v(pVar.M, this.f138n, pVar.h, this.q, pVar.s, pVar.p, pVar.r, pVar.f));
        this.s = com.google.android.libraries.navigation.internal.afr.e.d(com.google.android.libraries.navigation.internal.pu.ap.a);
        this.t = com.google.android.libraries.navigation.internal.afr.e.d(com.google.android.libraries.navigation.internal.pu.w.a);
        this.u = com.google.android.libraries.navigation.internal.afr.g.b(anVar3);
        com.google.android.libraries.navigation.internal.afr.f fVarB2 = com.google.android.libraries.navigation.internal.afr.g.b(anVar2);
        this.v = fVarB2;
        this.w = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.ac(fVarB2, this.s));
        this.x = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.ar(com.google.android.libraries.navigation.internal.qs.b.a));
        this.y = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.at(pVar.r, pVar.e, pVar.f, pVar.q));
        com.google.android.libraries.navigation.internal.afr.k kVarD2 = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.t(pVar.t));
        this.z = kVarD2;
        this.A = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.u(kVarD2, this.g, pVar.B));
        this.B = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.l(pVar.q));
        this.C = com.google.android.libraries.navigation.internal.afr.g.b(bool);
        this.D = com.google.android.libraries.navigation.internal.afr.g.b(anVar6);
        this.E = com.google.android.libraries.navigation.internal.afr.g.b(anVar7);
        this.F = com.google.android.libraries.navigation.internal.afr.g.b(anVar8);
        this.G = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.af(pVar.C, this.b, this.c, pVar.c, this.f, this.g, this.i, this.k, this.r, this.q, pVar.d, pVar.l, pVar.h, pVar.q, pVar.w, pVar.B, pVar.e, pVar.r, pVar.t, this.s, pVar.j, this.j, pVar.y, pVar.g, pVar.i, pVar.z, this.t, pVar.v, pVar.f142n, pVar.m, pVar.f, pVar.A, pVar.O, com.google.android.libraries.navigation.internal.hy.p.a, pVar.E, pVar.G, this.u, this.w, pVar.F, pVar.D, pVar.P, this.x, this.y, pVar.x, this.A, this.B, this.C, this.D, this.E, this.F, go.a));
        this.H = com.google.android.libraries.navigation.internal.afr.g.b(wVar);
        com.google.android.libraries.navigation.internal.afr.k kVarD3 = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.an(this.b, this.c, this.d, this.f, this.G, pVar.F, pVar.E, this.g, this.i, this.r, this.s, this.q, this.x, pVar.h, pVar.e, pVar.r, pVar.H, pVar.y, pVar.f, pVar.A, pVar.q, pVar.B, pVar.x, this.H));
        this.I = kVarD3;
        this.J = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.ak(kVarD3));
        com.google.android.libraries.navigation.internal.afr.k kVarD4 = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.ag(this.I));
        this.K = kVarD4;
        com.google.android.libraries.navigation.internal.afr.k kVarD5 = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.aw(kVarD4));
        this.L = kVarD5;
        com.google.android.libraries.navigation.internal.rl.v vVar = new com.google.android.libraries.navigation.internal.rl.v(kVarD5, this.t);
        this.M = vVar;
        this.N = com.google.android.libraries.navigation.internal.afr.e.d(vVar);
        this.O = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.ai(this.I));
        com.google.android.libraries.navigation.internal.afr.k kVarD6 = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.aj(pVar.B, this.I, this.O));
        this.P = kVarD6;
        com.google.android.libraries.navigation.internal.rh.q qVar = new com.google.android.libraries.navigation.internal.rh.q(this.K, this.N, kVarD6, pVar.Q);
        this.Q = qVar;
        com.google.android.libraries.navigation.internal.afr.k kVarD7 = com.google.android.libraries.navigation.internal.afr.e.d(qVar);
        this.R = kVarD7;
        com.google.android.libraries.navigation.internal.rj.h hVar = new com.google.android.libraries.navigation.internal.rj.h(kVarD7, this.N);
        this.S = hVar;
        this.T = com.google.android.libraries.navigation.internal.afr.e.d(hVar);
        com.google.android.libraries.navigation.internal.afr.k kVarD8 = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.ae(this.G));
        this.U = kVarD8;
        this.V = new com.google.android.libraries.navigation.internal.rf.d(kVarD8, this.I);
        com.google.android.libraries.navigation.internal.afr.k kVarD9 = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.av(this.c, pVar.I, pVar.B));
        this.W = kVarD9;
        com.google.android.libraries.navigation.internal.afr.k kVarD10 = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.s(this.V, kVarD9, this.r, pVar.q, pVar.B));
        this.X = kVarD10;
        com.google.android.libraries.navigation.internal.re.g gVar = new com.google.android.libraries.navigation.internal.re.g(this.J, this.N, this.O, kVarD10, pVar.B);
        this.Y = gVar;
        this.Z = com.google.android.libraries.navigation.internal.afr.e.d(gVar);
        this.aa = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.ao(pVar.j, this.I, pVar.J));
        this.ab = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.ah(this.I));
        this.ac = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.al(pVar.e, pVar.j));
        com.google.android.libraries.navigation.internal.afr.f fVarB3 = com.google.android.libraries.navigation.internal.afr.g.b(anVar4);
        this.ad = fVarB3;
        com.google.android.libraries.navigation.internal.afr.k kVarD11 = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.ab(this.u, this.c, this.ac, fVarB3, this.X));
        this.ae = kVarD11;
        com.google.android.libraries.navigation.internal.afr.k kVarD12 = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.aa(this.G, kVarD11, pVar.q, pVar.B, this.W));
        this.af = kVarD12;
        com.google.android.libraries.navigation.internal.ri.g gVar2 = new com.google.android.libraries.navigation.internal.ri.g(this.ab, this.y, this.ae, kVarD12);
        this.ag = gVar2;
        this.ah = com.google.android.libraries.navigation.internal.afr.e.d(gVar2);
        com.google.android.libraries.navigation.internal.afr.k kVarD13 = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.ad(this.I));
        this.ai = kVarD13;
        this.aj = new com.google.android.libraries.navigation.internal.rl.b(kVarD13);
        this.ak = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.rk.h(this.I));
        com.google.android.libraries.navigation.internal.afr.k kVarD14 = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.au(pVar.B, this.W, this.ak));
        this.al = kVarD14;
        this.am = com.google.android.libraries.navigation.internal.afr.e.d(new com.google.android.libraries.navigation.internal.pu.d(this.I, this.J, this.r, this.j, this.y, this.q, this.T, this.Z, this.g, this.U, this.aa, this.s, this.i, this.f, this.ah, this.X, this.R, this.P, this.aj, kVarD14, this.z, this.O, this.A, this.W, pVar.I, pVar.J, pVar.B, this.B));
    }

    @Override // com.google.android.libraries.navigation.internal.pu.b
    public final com.google.android.libraries.navigation.internal.oo.b a() {
        return (com.google.android.libraries.navigation.internal.oo.b) this.am.a();
    }
}
