package com.google.android.libraries.navigation.internal.df;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes7.dex */
public enum e {
    DEVICE_MAGNETOMETER_ACCURACY,
    MAGNETIC_FIELD_STRENGTH_DIFF_FROM_IDEAL_MICROT,
    MAGNETIC_FIELD_STRENGTH_DEVIATION,
    CORRELATION_BETWEEN_DEVICE_AND_GYRO_ORIENTATION_CHANGES,
    RMS_DIFF_BETWEEN_DEVICE_AND_GYRO_ORIENTATION_CHANGES,
    CROSS_BETWEEN_ORIENTATION_CORRELATION_AND_ORIENTATION_RMS_DIFF,
    CROSS_BETWEEN_MAG_STRENGTH_DIFF_AND_MAG_STRENGTH_DEVIATION
}
