package com.google.android.libraries.navigation.internal.bu;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes7.dex */
public enum a {
    GOOD_TO_GO,
    JP_ELECTRONIC_TOLL_COLLECTION_CARD,
    JP_ELECTRONIC_TOLL_COLLECTION_CARD_V2,
    AVOID_HIGHWAYS,
    AVOID_TOLLS,
    PREFER_FUEL_EFFICIENT_ROUTING,
    AVOID_FERRIES,
    AVOID_ODD_EVEN_ROADS,
    AVOID_RODIZIO_AREAS,
    AVOID_MANILA_NUMBER_CODING_ROADS,
    AVOID_SANTIAGO_SELLO_VERDE_ROADS,
    TRIP_ORDER,
    TARGET_DISTANCE,
    AVOID_WHEELCHAIR_INACCESSIBLE_ROUTES,
    SEE_TOLL_PASS_PRICES,
    ENERGY_CONSUMPTION_ENGINE_TYPE,
    PREFERRED_VEHICLE_KEY,
    PREFER_HOV
}
