package com.google.android.libraries.navigation.internal.dw;

import com.google.android.libraries.navigation.R;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes7.dex */
public final class h {
    public static final int A;
    public static final int B;
    public static final int C;
    public static final int D;
    public static final int E;
    public static final int F;
    public static final int G;
    public static final int H;
    public static final int I;
    public static final int J;
    public static final int K;
    public static final int L;
    public static final int M;
    public static final int N;
    public static final int O;
    public static final int P;
    public static final int Q;
    public static final int R;
    public static final int S;
    public static final int T;
    public static final int U;
    public static final int V;
    public static final int W;
    public static final int X;
    public static final int Y;
    public static final int Z;
    public static final int a;
    public static final int aA;
    public static final int aB;
    public static final int aC;
    public static final int aD;
    public static final int aE;
    public static final int aF;
    public static final int aG;
    public static final int aH;
    public static final int aI;
    public static final int aJ;
    public static final int aK;
    public static final int aL;
    public static final int aM;
    public static final int aN;
    public static final int aO;
    public static final int aP;
    public static final int aQ;
    public static final int aR;
    public static final int aS;
    public static final int aT;
    public static final int aU;
    public static final int aV;
    public static final int aW;
    public static final int aX;
    public static final int aY;
    public static final int aZ;
    public static final int aa;
    public static final int ab;
    public static final int ac;
    public static final int ad;
    public static final int ae;
    public static final int af;
    public static final int ag;
    public static final int ah;
    public static final int ai;
    public static final int aj;
    public static final int ak;
    public static final int al;
    public static final int am;
    public static final int an;
    public static final int ao;
    public static final int ap;
    public static final int aq;
    public static final int ar;
    public static final int as;
    public static final int at;
    public static final int au;
    public static final int av;
    public static final int aw;
    public static final int ax;
    public static final int ay;
    public static final int az;
    public static final int b;
    public static final int ba;
    public static final int bb;
    public static final int bc;
    public static final int bd;
    public static final int be;
    public static final int bf;
    public static final int bg;
    public static final int bh;
    public static final int bi;
    public static final int bj;
    public static final int bk;
    public static final int bl;
    public static final int bm;
    public static final int bn;
    public static final int bo;
    public static final int bp;
    public static final int bq;
    public static final int c;
    public static final int d;
    public static final int e;
    public static final int f;
    public static final int g;
    public static final int h;
    public static final int i;
    public static final int j;
    public static final int k;
    public static final int l;
    public static final int m;

    /* JADX INFO: renamed from: n, reason: collision with root package name */
    public static final int f419n;
    public static final int o;
    public static final int p;
    public static final int q;
    public static final int r;
    public static final int s;
    public static final int t;
    public static final int u;
    public static final int v;
    public static final int w;
    public static final int x;
    public static final int y;
    public static final int z;

    static {
        int i2 = R.string.ABOUT;
        a = R.string.DA_AT;
        b = R.string.DA_DATA_CONNECTION_LOST;
        c = R.string.DA_DESTINATION_REACHED;
        d = R.string.DA_EXIT_NAME;
        e = R.string.DA_EXIT_NUMBER;
        f = R.string.DA_EXPANDED_NOTIFICATION_SUBTEXT;
        g = R.string.DA_LOCKSCREEN_NOTIFICATION_DIRECTIONS;
        h = R.string.DA_LOCKSCREEN_NOTIFICATION_SUBTEXT;
        i = R.string.DA_NAME_DELIMITER;
        j = R.string.DA_NOTIFICATION_STEP_FORMAT;
        k = R.string.DA_ONTO;
        l = R.string.DA_REROUTING;
        m = R.string.DA_ROUTE_PREFIXES;
        f419n = R.string.DA_ROUTE_SUFFIXES;
        o = R.string.DA_SPEECH_CONTINUE_FOR_A_HALF_MILE;
        p = R.string.DA_SPEECH_CONTINUE_FOR_A_QUARTER_MILE;
        q = R.string.DA_SPEECH_CONTINUE_FOR_ONE_AND_A_HALF_KILOMETERS;
        r = R.string.DA_SPEECH_CONTINUE_FOR_ONE_AND_A_HALF_MILES;
        s = R.string.DA_SPEECH_CONTINUE_FOR_THREE_QUARTERS_OF_A_MILE;
        t = R.string.DA_SPEECH_CONTINUE_ON_ROAD_FOR_A_HALF_MILE;
        u = R.string.DA_SPEECH_CONTINUE_ON_ROAD_FOR_A_QUARTER_MILE;
        v = R.string.DA_SPEECH_CONTINUE_ON_ROAD_FOR_ONE_AND_A_HALF_KILOMETERS;
        w = R.string.DA_SPEECH_CONTINUE_ON_ROAD_FOR_ONE_AND_A_HALF_MILES;
        x = R.string.DA_SPEECH_CONTINUE_ON_ROAD_FOR_THREE_QUARTERS_OF_A_MILE;
        y = R.string.DA_SPEECH_IN_A_HALF_MILE;
        z = R.string.DA_SPEECH_IN_A_QUARTER_MILE;
        A = R.string.DA_SPEECH_IN_ONE_AND_A_HALF_KILOMETERS;
        B = R.string.DA_SPEECH_IN_ONE_AND_A_HALF_MILES;
        C = R.string.DA_SPEECH_IN_THREE_QUARTERS_OF_A_MILE;
        D = R.string.DA_SPEECH_LOST_GPS;
        E = R.string.DA_SPEECH_YOU_SHOULD_GET_THERE_BY;
        F = R.string.DA_SPEECH_YOU_WILL_NOW_ARRIVE_AT;
        G = R.string.DA_STAY_ON_ROAD_PRIMARY;
        H = R.string.DA_STAY_ON_ROAD_SECONDARY_MANEUVER;
        I = R.string.DA_THEN;
        J = R.string.DA_TOWARD;
        K = R.string.DA_YOUR_DESTINATION_IS_A_HALF_MILE_AHEAD;
        L = R.string.DA_YOUR_DESTINATION_IS_A_QUARTER_MILE_AHEAD;
        M = R.string.DA_YOUR_DESTINATION_IS_ONE_AND_A_HALF_KILOMETERS_AHEAD;
        N = R.string.DA_YOUR_DESTINATION_IS_ONE_AND_A_HALF_MILES_AHEAD;
        O = R.string.DA_YOUR_DESTINATION_IS_THREE_QUARTERS_OF_A_MILE_AHEAD;
        P = R.string.DONE;
        Q = R.string.DRIVING_MODE_NOTIFICATION_DRIVING_WITH_NO_CURRENT_ROAD;
        R = R.string.DURATION_AND_DISTANCE_TO_DESTINATION;
        S = R.string.DURATION_AND_DISTANCE_WITH_DESTINATION;
        T = R.string.EYES_FREE_MODE_REROUTE_NOTIFICATION;
        U = R.string.INCIDENT_CALLOUT_PROMPT_REPORTED_TEXT;
        V = R.string.INCIDENT_CALLOUT_PROMPT_SELF_REPORT_TEXT;
        W = R.string.INITIAL_NOTIFICATION_CONTENT_TITLE;
        X = R.string.MENU_SHOW_REPORT_INCIDENT;
        Y = R.string.MIDTRIP_UGC_COOLDOWN_HEADER_TEXT;
        Z = R.string.MIDTRIP_UGC_COOLDOWN_TEXT;
        aa = R.string.MIDTRIP_UGC_VOTE_CAN_YOU_SEE_THIS;
        ab = R.string.MIDTRIP_UGC_VOTE_IS_THE_ROAD_CLOSED;
        ac = R.string.MIDTRIP_UGC_VOTE_NO;
        ad = R.string.MIDTRIP_UGC_VOTE_NOT_THERE;
        ae = R.string.MIDTRIP_UGC_VOTE_PROMPT_INCIDENT_AHEAD_TITLE;
        af = R.string.MIDTRIP_UGC_VOTE_PROMPT_INCIDENT_NEARBY_TITLE;
        ag = R.string.MIDTRIP_UGC_VOTE_REPORTS_EXTENDED_COUNT_TEXT;
        ah = R.string.MIDTRIP_UGC_VOTE_REPORTS_EXTENDED_TIME_AGO_TEXT;
        ai = R.string.MIDTRIP_UGC_VOTE_REPORTS_TIME_AGO_TEXT;
        aj = R.string.MIDTRIP_UGC_VOTE_REPORTS_TIME_JUST_NOW_TEXT;
        ak = R.string.MIDTRIP_UGC_VOTE_SAFETY_TEXT;
        al = R.string.MIDTRIP_UGC_VOTE_SENT_FEEDBACK;
        am = R.string.MIDTRIP_UGC_VOTE_STILL_THERE;
        an = R.string.MIDTRIP_UGC_VOTE_YES;
        ao = R.string.NAVIGATION_STEP_LIST_DISTANCE_TO_NEXT_STEP;
        ap = R.string.POI_PROMPT_ADD_STOP;
        aq = R.string.POI_PROMPT_ADD_STOP_ACTION;
        ar = R.string.POI_PROMPT_NAVIGATE;
        as = R.string.POI_PROMPT_NAVIGATE_ACTION;
        at = R.string.PROMPT_CANCEL;
        au = R.string.PROMPT_DISMISS;
        av = R.string.RECENTER_FOLLOW_MODE;
        aw = R.string.REPORT_INCIDENT_BUTTON_LABEL_NAV_API;
        ax = R.string.REPORT_INCIDENT_PROMPT_ACCIDENT;
        ay = R.string.REPORT_INCIDENT_PROMPT_ACCIDENT_REPORTED;
        az = R.string.REPORT_INCIDENT_PROMPT_ACCIDENT_REPORTING;
        aA = R.string.REPORT_INCIDENT_PROMPT_CAMERA;
        aB = R.string.REPORT_INCIDENT_PROMPT_CAMERA_REPORTED;
        aC = R.string.REPORT_INCIDENT_PROMPT_CAMERA_REPORTING;
        aD = R.string.REPORT_INCIDENT_PROMPT_CONSTRUCTION;
        aE = R.string.REPORT_INCIDENT_PROMPT_CONSTRUCTION_REPORTED;
        aF = R.string.REPORT_INCIDENT_PROMPT_CONSTRUCTION_REPORTING;
        aG = R.string.REPORT_INCIDENT_PROMPT_DISABLED_VEHICLE;
        aH = R.string.REPORT_INCIDENT_PROMPT_DISABLED_VEHICLE_REPORTED;
        aI = R.string.REPORT_INCIDENT_PROMPT_DISABLED_VEHICLE_REPORTING;
        aJ = R.string.REPORT_INCIDENT_PROMPT_JAM;
        aK = R.string.REPORT_INCIDENT_PROMPT_JAM_REPORTED;
        aL = R.string.REPORT_INCIDENT_PROMPT_JAM_REPORTING;
        aM = R.string.REPORT_INCIDENT_PROMPT_LANE_CLOSURE;
        aN = R.string.REPORT_INCIDENT_PROMPT_LANE_CLOSURE_REPORTED;
        aO = R.string.REPORT_INCIDENT_PROMPT_LANE_CLOSURE_REPORTING;
        aP = R.string.REPORT_INCIDENT_PROMPT_MOBILE_SPEED_CAMERA;
        aQ = R.string.REPORT_INCIDENT_PROMPT_MOBILE_SPEED_CAMERA_REPORTED;
        aR = R.string.REPORT_INCIDENT_PROMPT_MOBILE_SPEED_CAMERA_REPORTING;
        aS = R.string.REPORT_INCIDENT_PROMPT_OBJECT_ON_ROAD;
        aT = R.string.REPORT_INCIDENT_PROMPT_OBJECT_ON_ROAD_REPORTED;
        aU = R.string.REPORT_INCIDENT_PROMPT_OBJECT_ON_ROAD_REPORTING;
        aV = R.string.REPORT_INCIDENT_PROMPT_POLICE;
        aW = R.string.REPORT_INCIDENT_PROMPT_POLICE_REPORTED;
        aX = R.string.REPORT_INCIDENT_PROMPT_POLICE_REPORTING;
        aY = R.string.REPORT_INCIDENT_PROMPT_SAFETY_TEXT;
        aZ = R.string.REPORT_INCIDENT_PROMPT_SPEED_TRAP;
        ba = R.string.REPORT_INCIDENT_PROMPT_SPEED_TRAP_REPORTED;
        bb = R.string.REPORT_INCIDENT_PROMPT_SPEED_TRAP_REPORTING;
        bc = R.string.REPORT_INCIDENT_PROMPT_THANKS;
        bd = R.string.REPORT_INCIDENT_PROMPT_TITLE;
        be = R.string.REPORT_INCIDENT_PROMPT_UNDO;
        bf = R.string.ROUTE_AROUND_TRAFFIC_ACTION;
        bg = R.string.ROUTE_AROUND_TRAFFIC_DECLINE;
        bh = R.string.ROUTE_AROUND_TRAFFIC_REROUTE;
        bi = R.string.ROUTE_AROUND_TRAFFIC_TAKE_ACTION_CUE_DEFAULT_DECLINE;
        bj = R.string.ROUTE_AROUND_TRAFFIC_TAKE_ACTION_CUE_DEFAULT_REROUTE;
        bk = R.string.SPEEDOMETER_CONTENT_DESCRIPTION;
        bl = R.string.SPEEDOMETER_LABEL_MPH;
        bm = R.string.SPEED_LIMIT_CONTENT_DESCRIPTION;
        bn = R.string.SPEED_LIMIT_LABEL_KPH;
        bo = R.string.SPEED_LIMIT_LABEL_MPH;
        bp = R.string.STEP_LIST_INTERACTION_LOCKOUT;
        bq = R.string.TRAFFIC_UPDATE_ETA_PROMPT_SUBTITLE;
    }
}
