package com.google.android.libraries.navigation.internal.qk;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes7.dex */
public enum t {
    NAVIGATION_SEARCH_RESULT,
    REMOVE_WAYPOINT,
    END_OF_RANGE,
    LARGE_VEHICLE_IMPASSABLE_RESTRICTIONS,
    LARGE_VEHICLE_HIGH_PRIORITY_INFORMATION,
    FLYOVER,
    NARROW_ROAD,
    NAVIGATION_MANEUVER,
    ASSISTED_DRIVING,
    TRANSIT_VEHICLE,
    BIKESHARING,
    POLYLINE_DECORATION_EXPANDED,
    POLYLINE_DECORATION_LIMITED_SPACE,
    ROUTE_DURATION,
    IMPLICIT_DESTINATION,
    JAMCIDENTS,
    LARGE_VEHICLE_LOW_PRIORITY_INFORMATION,
    LARGE_VEHICLE_PASSABLE_RESTRICTIONS,
    POLYLINE_DECORATION,
    DIRECTIONS_MANEUVER,
    ENTRANCE_MANEUVER,
    DETAILED_ENTRANCE,
    DRAGGABLE_ENTRANCE,
    ARRIVAL_ISSUE_NOTIFICATION,
    PLACEMARK,
    TAXI,
    TRANSIT_REALTIME,
    TRANSIT_ROUTE,
    POST_TRIP_UGC_MANEUVER,
    NON_TRAFFIC_INCIDENT,
    YOU_ARE_HERE,
    FOR_TESTING
}
