package com.google.android.libraries.navigation.internal.aaz;

import com.google.android.libraries.navigation.internal.yz.ez;
import com.google.android.libraries.navigation.internal.yz.fd;
import com.google.android.libraries.navigation.internal.yz.fy;

/* JADX WARN: Enum visitor error
jadx.core.utils.exceptions.JadxRuntimeException: Can't remove SSA var: r4v0 com.google.android.libraries.navigation.internal.aaz.a, still in use, count: 1, list:
  (r4v0 com.google.android.libraries.navigation.internal.aaz.a) from 0x0d7c: INVOKE 
  (r4v0 com.google.android.libraries.navigation.internal.aaz.a)
  (r5v0 com.google.android.libraries.navigation.internal.aaz.a)
  (r6v0 com.google.android.libraries.navigation.internal.aaz.a)
  (r7v0 com.google.android.libraries.navigation.internal.aaz.a)
  (r8v0 com.google.android.libraries.navigation.internal.aaz.a)
  (r9v0 com.google.android.libraries.navigation.internal.aaz.a)
  (wrap com.google.android.libraries.navigation.internal.aaz.a[]:0x0d78: FILLED_NEW_ARRAY 
  (r10v0 com.google.android.libraries.navigation.internal.aaz.a)
  (r11v0 com.google.android.libraries.navigation.internal.aaz.a)
  (r12v0 com.google.android.libraries.navigation.internal.aaz.a)
  (r13v0 com.google.android.libraries.navigation.internal.aaz.a)
  (r14v0 com.google.android.libraries.navigation.internal.aaz.a)
  (r15v0 com.google.android.libraries.navigation.internal.aaz.a)
 A[WRAPPED] elemType: com.google.android.libraries.navigation.internal.aaz.a)
 STATIC call: com.google.android.libraries.navigation.internal.yz.fy.u(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object[]):com.google.android.libraries.navigation.internal.yz.fy A[MD:(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object[]):com.google.android.libraries.navigation.internal.yz.fy VARARG (m), VARARG_CALL] (LINE:310)
	at jadx.core.utils.InsnRemover.removeSsaVar(InsnRemover.java:164)
	at jadx.core.utils.InsnRemover.unbindResult(InsnRemover.java:129)
	at jadx.core.utils.InsnRemover.lambda$unbindInsns$1(InsnRemover.java:101)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at jadx.core.utils.InsnRemover.unbindInsns(InsnRemover.java:100)
	at jadx.core.utils.InsnRemover.removeAllAndUnbind(InsnRemover.java:257)
	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:187)
	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:102)
 */
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes7.dex */
public final class a {
    AC,
    AD,
    AE,
    AF,
    AG,
    AI,
    AL,
    AM,
    AN,
    AO,
    AQ,
    AR,
    AS,
    AT,
    AU,
    AW,
    AX,
    AZ,
    BA,
    BB,
    BD,
    BE,
    BF,
    BG,
    BH,
    BI,
    BJ,
    BL,
    BM,
    BN,
    BO,
    BQ,
    BR,
    BS,
    BT,
    BU,
    BV,
    BW,
    BY,
    BZ,
    CA,
    CC,
    CD,
    CF,
    CG,
    CH,
    CI,
    CK,
    CL,
    CM,
    CN,
    CO,
    CP,
    CQ,
    CR,
    CS,
    CU,
    CV,
    CW,
    CX,
    CY,
    CZ,
    DD,
    DE,
    DG,
    DJ,
    DK,
    DM,
    DO,
    DZ,
    EA,
    EC,
    EE,
    EG,
    EH,
    ER,
    ES,
    ET,
    EU,
    EZ,
    FI,
    FJ,
    FK,
    FM,
    FO,
    FR,
    FX,
    GA,
    GB,
    GD,
    GE,
    GF,
    GG,
    GH,
    GI,
    GL,
    GM,
    GN,
    GP,
    GQ,
    GR,
    GS,
    GT,
    GU,
    GW,
    GY,
    HK,
    HM,
    HN,
    HR,
    HT,
    HU,
    IC,
    ID,
    IE,
    IL,
    IM,
    IN,
    IO,
    IQ,
    IR,
    IS,
    IT,
    JE,
    JM,
    JO,
    JP,
    KE,
    KG,
    KH,
    KI,
    KM,
    KN,
    KP,
    KR,
    KW,
    KY,
    KZ,
    LA,
    LB,
    LC,
    LI,
    LK,
    LR,
    LS,
    LT,
    LU,
    LV,
    LY,
    MA,
    MC,
    MD,
    ME,
    MF,
    MG,
    MH,
    MK,
    ML,
    MM,
    MN,
    MO,
    MP,
    MQ,
    MR,
    MS,
    MT,
    MU,
    MV,
    MW,
    MX,
    MY,
    MZ,
    NA,
    NC,
    NE,
    NF,
    NG,
    NI,
    NL,
    NO,
    NP,
    NR,
    NT,
    NU,
    NZ,
    OM,
    PA,
    PE,
    PF,
    PG,
    PH,
    PK,
    PL,
    PM,
    PN,
    PR,
    PS,
    PT,
    PW,
    PY,
    QA,
    QO,
    QU,
    RE,
    RO,
    RS,
    RU,
    RW,
    SA,
    SB,
    SC,
    SD,
    SE,
    SG,
    SH,
    SI,
    SJ,
    SK,
    SL,
    SM,
    SN,
    SO,
    SR,
    SS,
    ST,
    SU,
    SV,
    SX,
    SY,
    SZ,
    TA,
    TC,
    TD,
    TF,
    TG,
    TH,
    TJ,
    TK,
    TL,
    TM,
    TN,
    TO,
    TP,
    TR,
    TT,
    TV,
    TW,
    TZ,
    UA,
    UG,
    UM,
    UN,
    US,
    UY,
    UZ,
    VA,
    VC,
    VE,
    VG,
    VI,
    VN,
    VU,
    WF,
    WS,
    XA,
    XB,
    XC,
    XK,
    YD,
    YE,
    YT,
    YU,
    ZA,
    ZM,
    ZR,
    ZW,
    ZZ,
    UN001("001"),
    UN002("002"),
    UN003("003"),
    UN005("005"),
    UN009("009"),
    UN011("011"),
    UN013("013"),
    UN014("014"),
    UN015("015"),
    UN017("017"),
    UN018("018"),
    UN019("019"),
    UN021("021"),
    UN029("029"),
    UN030("030"),
    UN034("034"),
    UN035("035"),
    UN039("039"),
    UN053("053"),
    UN054("054"),
    UN057("057"),
    UN061("061"),
    UN142("142"),
    UN143("143"),
    UN145("145"),
    UN150("150"),
    UN151("151"),
    UN154("154"),
    UN155("155"),
    UN202("202"),
    UN419("419");

    public static final fd eW;
    private final String eY;

    static {
        fy.u(new a(), new a(), new a(), new a(), new a(), new a(), new a(), new a(), new a(), new a(), new a(), new a());
        fy.w();
        a[] aVarArrValues = values();
        ez ezVar = new ez();
        for (a aVar : aVarArrValues) {
            ezVar.f(aVar.toString(), aVar);
        }
        ezVar.f("UK", GB);
        eW = ezVar.d();
    }

    private a() {
        super(str, i);
        this.eY = name();
    }

    public static a[] values() {
        return (a[]) eX.clone();
    }

    @Override // java.lang.Enum
    public final String toString() {
        return this.eY;
    }

    private a(String str) {
        super(str, i);
        this.eY = str;
    }
}
