package com.google.android.libraries.navigation.internal.ko;

import com.google.android.libraries.navigation.internal.yz.fd;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes7.dex */
public final class a {
    public static final fd a = fd.l(com.google.android.libraries.navigation.internal.kn.a.PRIMARY_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Cold Startup - activity onCreate to First Map Tile"), com.google.android.libraries.navigation.internal.kn.a.AUXILIARY_CLUSTER_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Cold Startup - activity onCreate to First Map Tile: AUXILIARY_CLUSTER_MAP"));
    public static final fd b = fd.l(com.google.android.libraries.navigation.internal.kn.a.PRIMARY_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Warm Startup - activity onCreate to First Map Tile"), com.google.android.libraries.navigation.internal.kn.a.AUXILIARY_CLUSTER_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Warm Startup - activity onCreate to First Map Tile: AUXILIARY_CLUSTER_MAP"));
    public static final fd c = fd.l(com.google.android.libraries.navigation.internal.kn.a.PRIMARY_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Cold Startup - activity onCreate to All Base Tiles"), com.google.android.libraries.navigation.internal.kn.a.AUXILIARY_CLUSTER_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Cold Startup - activity onCreate to All Base Tiles: AUXILIARY_CLUSTER_MAP"));
    public static final fd d = fd.l(com.google.android.libraries.navigation.internal.kn.a.PRIMARY_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Warm Startup - activity onCreate to All Base Tiles"), com.google.android.libraries.navigation.internal.kn.a.AUXILIARY_CLUSTER_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Warm Startup - activity onCreate to All Base Tiles: AUXILIARY_CLUSTER_MAP"));
    public static final fd e = fd.l(com.google.android.libraries.navigation.internal.kn.a.PRIMARY_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Cold Startup - activity onCreate to All Base Labels"), com.google.android.libraries.navigation.internal.kn.a.AUXILIARY_CLUSTER_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Cold Startup - activity onCreate to All Base Labels: AUXILIARY_CLUSTER_MAP"));
    public static final fd f = fd.l(com.google.android.libraries.navigation.internal.kn.a.PRIMARY_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Warm Startup - activity onCreate to All Base Labels"), com.google.android.libraries.navigation.internal.kn.a.AUXILIARY_CLUSTER_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Warm Startup - activity onCreate to All Base Labels: AUXILIARY_CLUSTER_MAP"));
    public static final fd g = fd.l(com.google.android.libraries.navigation.internal.kn.a.PRIMARY_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Cold Startup - activity onCreate to Last Map Tile"), com.google.android.libraries.navigation.internal.kn.a.AUXILIARY_CLUSTER_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Cold Startup - activity onCreate to Last Map Tile: AUXILIARY_CLUSTER_MAP"));
    public static final fd h = fd.l(com.google.android.libraries.navigation.internal.kn.a.PRIMARY_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Cold Startup - activity onCreate to Last Map Label"), com.google.android.libraries.navigation.internal.kn.a.AUXILIARY_CLUSTER_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Cold Startup - activity onCreate to Last Map Label: AUXILIARY_CLUSTER_MAP"));
    public static final fd i = fd.l(com.google.android.libraries.navigation.internal.kn.a.PRIMARY_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Cold Startup - activity onCreate To Last Map Label Interrupted"), com.google.android.libraries.navigation.internal.kn.a.AUXILIARY_CLUSTER_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Cold Startup - activity onCreate To Last Map Label Interrupted: AUXILIARY_CLUSTER_MAP"));
    public static final fd j = fd.l(com.google.android.libraries.navigation.internal.kn.a.PRIMARY_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Cold Startup - activity onCreate To Last Map Tile Interrupted"), com.google.android.libraries.navigation.internal.kn.a.AUXILIARY_CLUSTER_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Cold Startup - activity onCreate To Last Map Tile Interrupted: AUXILIARY_CLUSTER_MAP"));
    public static final fd k = fd.l(com.google.android.libraries.navigation.internal.kn.a.PRIMARY_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Cold Startup - activity onCreate to Viewport Drawn"), com.google.android.libraries.navigation.internal.kn.a.AUXILIARY_CLUSTER_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Cold Startup - activity onCreate to Viewport Drawn: AUXILIARY_CLUSTER_MAP"));
    public static final fd l = fd.l(com.google.android.libraries.navigation.internal.kn.a.PRIMARY_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Warm Startup - activity onCreate to Last Map Tile"), com.google.android.libraries.navigation.internal.kn.a.AUXILIARY_CLUSTER_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Warm Startup - activity onCreate to Last Map Tile: AUXILIARY_CLUSTER_MAP"));
    public static final fd m = fd.l(com.google.android.libraries.navigation.internal.kn.a.PRIMARY_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Warm Startup - activity onCreate to Last Map Label"), com.google.android.libraries.navigation.internal.kn.a.AUXILIARY_CLUSTER_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Warm Startup - activity onCreate to Last Map Label: AUXILIARY_CLUSTER_MAP"));

    /* JADX INFO: renamed from: n, reason: collision with root package name */
    public static final fd f474n = fd.l(com.google.android.libraries.navigation.internal.kn.a.PRIMARY_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Warm Startup - activity onCreate to Viewport Drawn"), com.google.android.libraries.navigation.internal.kn.a.AUXILIARY_CLUSTER_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Warm Startup - activity onCreate to Viewport Drawn: AUXILIARY_CLUSTER_MAP"));
    public static final fd o;

    static {
        fd.l(com.google.android.libraries.navigation.internal.kn.a.PRIMARY_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Hot Startup - activity resumed"), com.google.android.libraries.navigation.internal.kn.a.AUXILIARY_CLUSTER_MAP, com.google.android.libraries.navigation.internal.xn.a.d("Hot Startup - activity resumed: AUXILIARY_CLUSTER_MAP"));
        o = fd.l(com.google.android.libraries.navigation.internal.kn.a.PRIMARY_MAP, com.google.android.libraries.navigation.internal.xn.a.d("OnLastLabelPlaced"), com.google.android.libraries.navigation.internal.kn.a.AUXILIARY_CLUSTER_MAP, com.google.android.libraries.navigation.internal.xn.a.d("OnLastLabelPlaced: AUXILIARY_CLUSTER_MAP"));
    }
}
