package com.google.android.libraries.navigation.internal.ju;

import android.graphics.Color;
import com.google.android.libraries.navigation.internal.af.e;
import com.google.android.libraries.navigation.internal.nc.ae;
import kotlin.jvm.internal.Intrinsics;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes7.dex */
public final class c {
    public static final com.google.android.libraries.navigation.internal.af.a A;
    public static final com.google.android.libraries.navigation.internal.af.a B;
    public static final com.google.android.libraries.navigation.internal.af.a C;
    public static final com.google.android.libraries.navigation.internal.af.a D;
    public static final com.google.android.libraries.navigation.internal.af.a E;
    public static final com.google.android.libraries.navigation.internal.af.a F;
    public static final com.google.android.libraries.navigation.internal.af.a G;
    public static final com.google.android.libraries.navigation.internal.af.a H;
    public static final com.google.android.libraries.navigation.internal.af.a I;
    public static final com.google.android.libraries.navigation.internal.af.a J;
    public static final com.google.android.libraries.navigation.internal.af.a K;
    public static final com.google.android.libraries.navigation.internal.af.a L;
    public static final com.google.android.libraries.navigation.internal.af.a M;
    public static final com.google.android.libraries.navigation.internal.af.a N;
    public static final com.google.android.libraries.navigation.internal.af.a O;
    public static final com.google.android.libraries.navigation.internal.af.a P;
    public static final com.google.android.libraries.navigation.internal.af.a Q;
    public static final com.google.android.libraries.navigation.internal.af.a R;
    public static final com.google.android.libraries.navigation.internal.af.a S;
    public static final com.google.android.libraries.navigation.internal.af.a T;
    public static final com.google.android.libraries.navigation.internal.af.a U;
    public static final com.google.android.libraries.navigation.internal.af.a V;
    public static final com.google.android.libraries.navigation.internal.af.a W;
    public static final com.google.android.libraries.navigation.internal.af.a X;
    public static final com.google.android.libraries.navigation.internal.af.a Y;
    public static final com.google.android.libraries.navigation.internal.af.a Z;
    public static final com.google.android.libraries.navigation.internal.af.a a;
    public static final com.google.android.libraries.navigation.internal.af.a aA;
    public static final com.google.android.libraries.navigation.internal.af.a aB;
    public static final com.google.android.libraries.navigation.internal.af.a aC;
    public static final com.google.android.libraries.navigation.internal.af.a aD;
    public static final com.google.android.libraries.navigation.internal.af.a aa;
    public static final com.google.android.libraries.navigation.internal.af.a ab;
    public static final com.google.android.libraries.navigation.internal.af.a ac;
    public static final com.google.android.libraries.navigation.internal.af.a ad;
    public static final com.google.android.libraries.navigation.internal.af.a ae;
    public static final com.google.android.libraries.navigation.internal.af.a af;
    public static final com.google.android.libraries.navigation.internal.af.a ag;
    public static final com.google.android.libraries.navigation.internal.af.a ah;
    public static final com.google.android.libraries.navigation.internal.af.a ai;
    public static final com.google.android.libraries.navigation.internal.af.a aj;
    public static final com.google.android.libraries.navigation.internal.af.a ak;
    public static final com.google.android.libraries.navigation.internal.af.a al;
    public static final com.google.android.libraries.navigation.internal.af.a am;
    public static final com.google.android.libraries.navigation.internal.af.a an;
    public static final com.google.android.libraries.navigation.internal.af.a ao;
    public static final com.google.android.libraries.navigation.internal.af.a ap;
    public static final com.google.android.libraries.navigation.internal.af.a aq;
    public static final com.google.android.libraries.navigation.internal.af.a ar;
    public static final com.google.android.libraries.navigation.internal.af.a as;
    public static final com.google.android.libraries.navigation.internal.af.a at;
    public static final com.google.android.libraries.navigation.internal.af.a au;
    public static final com.google.android.libraries.navigation.internal.af.a av;
    public static final com.google.android.libraries.navigation.internal.af.a aw;
    public static final com.google.android.libraries.navigation.internal.af.a ax;
    public static final com.google.android.libraries.navigation.internal.af.a ay;
    public static final com.google.android.libraries.navigation.internal.af.a az;
    public static final com.google.android.libraries.navigation.internal.af.a b;
    public static final com.google.android.libraries.navigation.internal.af.a c;
    public static final com.google.android.libraries.navigation.internal.af.a d;
    public static final com.google.android.libraries.navigation.internal.af.a e;
    public static final com.google.android.libraries.navigation.internal.af.a f;
    public static final com.google.android.libraries.navigation.internal.af.a g;
    public static final com.google.android.libraries.navigation.internal.af.a h;
    public static final com.google.android.libraries.navigation.internal.af.a i;
    public static final com.google.android.libraries.navigation.internal.af.a j;
    public static final com.google.android.libraries.navigation.internal.af.a k;
    public static final com.google.android.libraries.navigation.internal.af.a l;
    public static final com.google.android.libraries.navigation.internal.af.a m;

    /* JADX INFO: renamed from: n, reason: collision with root package name */
    public static final com.google.android.libraries.navigation.internal.af.a f458n;
    public static final com.google.android.libraries.navigation.internal.af.a o;
    public static final com.google.android.libraries.navigation.internal.af.a p;
    public static final com.google.android.libraries.navigation.internal.af.a q;
    public static final com.google.android.libraries.navigation.internal.af.a r;
    public static final com.google.android.libraries.navigation.internal.af.a s;
    public static final com.google.android.libraries.navigation.internal.af.a t;
    public static final com.google.android.libraries.navigation.internal.af.a u;
    public static final com.google.android.libraries.navigation.internal.af.a v;
    public static final com.google.android.libraries.navigation.internal.af.a w;
    public static final com.google.android.libraries.navigation.internal.af.a x;
    public static final com.google.android.libraries.navigation.internal.af.a y;
    public static final com.google.android.libraries.navigation.internal.af.a z;

    static {
        ae aeVarD = ae.d(11693056);
        Intrinsics.checkNotNullExpressionValue(aeVarD, "rgb(...)");
        ae aeVarD2 = ae.d(16759593);
        Intrinsics.checkNotNullExpressionValue(aeVarD2, "rgb(...)");
        a = e.b(aeVarD, aeVarD2);
        ae aeVarD3 = ae.d(16708322);
        Intrinsics.checkNotNullExpressionValue(aeVarD3, "rgb(...)");
        ae aeVarD4 = ae.d(2432789);
        Intrinsics.checkNotNullExpressionValue(aeVarD4, "rgb(...)");
        b = e.b(aeVarD3, aeVarD4);
        ae aeVarD5 = ae.d(16768921);
        Intrinsics.checkNotNullExpressionValue(aeVarD5, "rgb(...)");
        ae aeVarD6 = ae.d(3877912);
        Intrinsics.checkNotNullExpressionValue(aeVarD6, "rgb(...)");
        c = e.b(aeVarD5, aeVarD6);
        ae aeVarD7 = ae.d(16759593);
        Intrinsics.checkNotNullExpressionValue(aeVarD7, "rgb(...)");
        ae aeVarD8 = ae.d(16768921);
        Intrinsics.checkNotNullExpressionValue(aeVarD8, "rgb(...)");
        d = e.b(aeVarD7, aeVarD8);
        ae aeVarD9 = ae.d(0);
        Intrinsics.checkNotNullExpressionValue(aeVarD9, "rgb(...)");
        ae aeVarD10 = ae.d(0);
        Intrinsics.checkNotNullExpressionValue(aeVarD10, "rgb(...)");
        e = e.b(aeVarD9, aeVarD10);
        ae aeVar = new ae(Color.argb(153, 0, 0, 0));
        Intrinsics.checkNotNullExpressionValue(aeVar, "argb(...)");
        ae aeVar2 = new ae(Color.argb(153, 0, 0, 0));
        Intrinsics.checkNotNullExpressionValue(aeVar2, "argb(...)");
        f = e.b(aeVar, aeVar2);
        ae aeVarD11 = ae.d(6184542);
        Intrinsics.checkNotNullExpressionValue(aeVarD11, "rgb(...)");
        ae aeVarD12 = ae.d(6184542);
        Intrinsics.checkNotNullExpressionValue(aeVarD12, "rgb(...)");
        g = e.b(aeVarD11, aeVarD12);
        ae aeVarD13 = ae.d(11061242);
        Intrinsics.checkNotNullExpressionValue(aeVarD13, "rgb(...)");
        ae aeVarD14 = ae.d(11061242);
        Intrinsics.checkNotNullExpressionValue(aeVarD14, "rgb(...)");
        h = e.b(aeVarD13, aeVarD14);
        ae aeVarD15 = ae.d(5592405);
        Intrinsics.checkNotNullExpressionValue(aeVarD15, "rgb(...)");
        ae aeVarD16 = ae.d(5592405);
        Intrinsics.checkNotNullExpressionValue(aeVarD16, "rgb(...)");
        i = e.b(aeVarD15, aeVarD16);
        ae aeVarD17 = ae.d(2697773);
        Intrinsics.checkNotNullExpressionValue(aeVarD17, "rgb(...)");
        ae aeVarD18 = ae.d(2697773);
        Intrinsics.checkNotNullExpressionValue(aeVarD18, "rgb(...)");
        j = e.b(aeVarD17, aeVarD18);
        ae aeVarD19 = ae.d(14935011);
        Intrinsics.checkNotNullExpressionValue(aeVarD19, "rgb(...)");
        ae aeVarD20 = ae.d(3158064);
        Intrinsics.checkNotNullExpressionValue(aeVarD20, "rgb(...)");
        k = e.b(aeVarD19, aeVarD20);
        ae aeVarD21 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD21, "rgb(...)");
        ae aeVarD22 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD22, "rgb(...)");
        l = e.b(aeVarD21, aeVarD22);
        ae aeVarD23 = ae.d(743376);
        Intrinsics.checkNotNullExpressionValue(aeVarD23, "rgb(...)");
        ae aeVarD24 = ae.d(11061242);
        Intrinsics.checkNotNullExpressionValue(aeVarD24, "rgb(...)");
        m = e.b(aeVarD23, aeVarD24);
        ae aeVarD25 = ae.d(15791353);
        Intrinsics.checkNotNullExpressionValue(aeVarD25, "rgb(...)");
        ae aeVarD26 = ae.d(1974048);
        Intrinsics.checkNotNullExpressionValue(aeVarD26, "rgb(...)");
        f458n = e.b(aeVarD25, aeVarD26);
        ae aeVarD27 = ae.d(11061242);
        Intrinsics.checkNotNullExpressionValue(aeVarD27, "rgb(...)");
        ae aeVarD28 = ae.d(743376);
        Intrinsics.checkNotNullExpressionValue(aeVarD28, "rgb(...)");
        o = e.b(aeVarD27, aeVarD28);
        ae aeVarD29 = ae.d(3158064);
        Intrinsics.checkNotNullExpressionValue(aeVarD29, "rgb(...)");
        ae aeVarD30 = ae.d(14935011);
        Intrinsics.checkNotNullExpressionValue(aeVarD30, "rgb(...)");
        p = e.b(aeVarD29, aeVarD30);
        ae aeVarD31 = ae.d(14899739);
        Intrinsics.checkNotNullExpressionValue(aeVarD31, "rgb(...)");
        ae aeVarD32 = ae.d(14899739);
        Intrinsics.checkNotNullExpressionValue(aeVarD32, "rgb(...)");
        q = e.b(aeVarD31, aeVarD32);
        ae aeVarD33 = ae.d(12927237);
        Intrinsics.checkNotNullExpressionValue(aeVarD33, "rgb(...)");
        ae aeVarD34 = ae.d(15821613);
        Intrinsics.checkNotNullExpressionValue(aeVarD34, "rgb(...)");
        r = e.b(aeVarD33, aeVarD34);
        ae aeVarD35 = ae.d(14431790);
        Intrinsics.checkNotNullExpressionValue(aeVarD35, "rgb(...)");
        ae aeVarD36 = ae.d(15906997);
        Intrinsics.checkNotNullExpressionValue(aeVarD36, "rgb(...)");
        s = e.b(aeVarD35, aeVarD36);
        ae aeVarD37 = ae.d(16773359);
        Intrinsics.checkNotNullExpressionValue(aeVarD37, "rgb(...)");
        ae aeVarD38 = ae.d(2628892);
        Intrinsics.checkNotNullExpressionValue(aeVarD38, "rgb(...)");
        t = e.b(aeVarD37, aeVarD38);
        ae aeVarD39 = ae.d(16375516);
        Intrinsics.checkNotNullExpressionValue(aeVarD39, "rgb(...)");
        ae aeVarD40 = ae.d(4399391);
        Intrinsics.checkNotNullExpressionValue(aeVarD40, "rgb(...)");
        u = e.b(aeVarD39, aeVarD40);
        ae aeVarD41 = ae.d(15921906);
        Intrinsics.checkNotNullExpressionValue(aeVarD41, "rgb(...)");
        ae aeVarD42 = ae.d(3158064);
        Intrinsics.checkNotNullExpressionValue(aeVarD42, "rgb(...)");
        v = e.b(aeVarD41, aeVarD42);
        ae aeVarD43 = ae.d(14541802);
        Intrinsics.checkNotNullExpressionValue(aeVarD43, "rgb(...)");
        ae aeVarD44 = ae.d(3355959);
        Intrinsics.checkNotNullExpressionValue(aeVarD44, "rgb(...)");
        w = e.b(aeVarD43, aeVarD44);
        ae aeVarD45 = ae.d(4333312);
        Intrinsics.checkNotNullExpressionValue(aeVarD45, "rgb(...)");
        ae aeVarD46 = ae.d(4333312);
        Intrinsics.checkNotNullExpressionValue(aeVarD46, "rgb(...)");
        x = e.b(aeVarD45, aeVarD46);
        ae aeVarD47 = ae.d(2039583);
        Intrinsics.checkNotNullExpressionValue(aeVarD47, "rgb(...)");
        ae aeVarD48 = ae.d(14935011);
        Intrinsics.checkNotNullExpressionValue(aeVarD48, "rgb(...)");
        y = e.b(aeVarD47, aeVarD48);
        ae aeVarD49 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD49, "rgb(...)");
        ae aeVarD50 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD50, "rgb(...)");
        z = e.b(aeVarD49, aeVarD50);
        ae aeVarD51 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD51, "rgb(...)");
        ae aeVarD52 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD52, "rgb(...)");
        A = e.b(aeVarD51, aeVarD52);
        ae aeVarD53 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD53, "rgb(...)");
        ae aeVarD54 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD54, "rgb(...)");
        B = e.b(aeVarD53, aeVarD54);
        ae aeVarD55 = ae.d(11250603);
        Intrinsics.checkNotNullExpressionValue(aeVarD55, "rgb(...)");
        ae aeVarD56 = ae.d(11250603);
        Intrinsics.checkNotNullExpressionValue(aeVarD56, "rgb(...)");
        C = e.b(aeVarD55, aeVarD56);
        ae aeVarD57 = ae.d(9408399);
        Intrinsics.checkNotNullExpressionValue(aeVarD57, "rgb(...)");
        ae aeVarD58 = ae.d(7697781);
        Intrinsics.checkNotNullExpressionValue(aeVarD58, "rgb(...)");
        D = e.b(aeVarD57, aeVarD58);
        ae aeVarD59 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD59, "rgb(...)");
        ae aeVarD60 = ae.d(269897);
        Intrinsics.checkNotNullExpressionValue(aeVarD60, "rgb(...)");
        E = e.b(aeVarD59, aeVarD60);
        ae aeVarD61 = ae.d(2039583);
        Intrinsics.checkNotNullExpressionValue(aeVarD61, "rgb(...)");
        ae aeVarD62 = ae.d(14935011);
        Intrinsics.checkNotNullExpressionValue(aeVarD62, "rgb(...)");
        F = e.b(aeVarD61, aeVarD62);
        ae aeVarD63 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD63, "rgb(...)");
        ae aeVarD64 = ae.d(2039583);
        Intrinsics.checkNotNullExpressionValue(aeVarD64, "rgb(...)");
        G = e.b(aeVarD63, aeVarD64);
        ae aeVarD65 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD65, "rgb(...)");
        ae aeVarD66 = ae.d(4263435);
        Intrinsics.checkNotNullExpressionValue(aeVarD66, "rgb(...)");
        H = e.b(aeVarD65, aeVarD66);
        ae aeVarD67 = ae.d(2039583);
        Intrinsics.checkNotNullExpressionValue(aeVarD67, "rgb(...)");
        ae aeVarD68 = ae.d(14935011);
        Intrinsics.checkNotNullExpressionValue(aeVarD68, "rgb(...)");
        I = e.b(aeVarD67, aeVarD68);
        ae aeVarD69 = ae.d(2039583);
        Intrinsics.checkNotNullExpressionValue(aeVarD69, "rgb(...)");
        ae aeVarD70 = ae.d(14935011);
        Intrinsics.checkNotNullExpressionValue(aeVarD70, "rgb(...)");
        J = e.b(aeVarD69, aeVarD70);
        ae aeVarD71 = ae.d(6184542);
        Intrinsics.checkNotNullExpressionValue(aeVarD71, "rgb(...)");
        ae aeVarD72 = ae.d(11250603);
        Intrinsics.checkNotNullExpressionValue(aeVarD72, "rgb(...)");
        K = e.b(aeVarD71, aeVarD72);
        ae aeVarD73 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD73, "rgb(...)");
        ae aeVarD74 = ae.d(468753);
        Intrinsics.checkNotNullExpressionValue(aeVarD74, "rgb(...)");
        L = e.b(aeVarD73, aeVarD74);
        ae aeVarD75 = ae.d(2039583);
        Intrinsics.checkNotNullExpressionValue(aeVarD75, "rgb(...)");
        ae aeVarD76 = ae.d(14935011);
        Intrinsics.checkNotNullExpressionValue(aeVarD76, "rgb(...)");
        M = e.b(aeVarD75, aeVarD76);
        ae aeVarD77 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD77, "rgb(...)");
        ae aeVarD78 = ae.d(269897);
        Intrinsics.checkNotNullExpressionValue(aeVarD78, "rgb(...)");
        N = e.b(aeVarD77, aeVarD78);
        ae aeVarD79 = ae.d(743376);
        Intrinsics.checkNotNullExpressionValue(aeVarD79, "rgb(...)");
        ae aeVarD80 = ae.d(13886461);
        Intrinsics.checkNotNullExpressionValue(aeVarD80, "rgb(...)");
        O = e.b(aeVarD79, aeVarD80);
        ae aeVarD81 = ae.d(269897);
        Intrinsics.checkNotNullExpressionValue(aeVarD81, "rgb(...)");
        ae aeVarD82 = ae.d(15528958);
        Intrinsics.checkNotNullExpressionValue(aeVarD82, "rgb(...)");
        P = e.b(aeVarD81, aeVarD82);
        ae aeVarD83 = ae.d(2039583);
        Intrinsics.checkNotNullExpressionValue(aeVarD83, "rgb(...)");
        ae aeVarD84 = ae.d(14935011);
        Intrinsics.checkNotNullExpressionValue(aeVarD84, "rgb(...)");
        Q = e.b(aeVarD83, aeVarD84);
        ae aeVarD85 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD85, "rgb(...)");
        ae aeVarD86 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD86, "rgb(...)");
        R = e.b(aeVarD85, aeVarD86);
        ae aeVarD87 = ae.d(2039583);
        Intrinsics.checkNotNullExpressionValue(aeVarD87, "rgb(...)");
        ae aeVarD88 = ae.d(14935011);
        Intrinsics.checkNotNullExpressionValue(aeVarD88, "rgb(...)");
        S = e.b(aeVarD87, aeVarD88);
        ae aeVarD89 = ae.d(6184542);
        Intrinsics.checkNotNullExpressionValue(aeVarD89, "rgb(...)");
        ae aeVarD90 = ae.d(11250603);
        Intrinsics.checkNotNullExpressionValue(aeVarD90, "rgb(...)");
        T = e.b(aeVarD89, aeVarD90);
        ae aeVarD91 = ae.d(2039583);
        Intrinsics.checkNotNullExpressionValue(aeVarD91, "rgb(...)");
        ae aeVarD92 = ae.d(14935011);
        Intrinsics.checkNotNullExpressionValue(aeVarD92, "rgb(...)");
        U = e.b(aeVarD91, aeVarD92);
        ae aeVarD93 = ae.d(14935011);
        Intrinsics.checkNotNullExpressionValue(aeVarD93, "rgb(...)");
        ae aeVarD94 = ae.d(4671303);
        Intrinsics.checkNotNullExpressionValue(aeVarD94, "rgb(...)");
        V = e.b(aeVarD93, aeVarD94);
        ae aeVarD95 = ae.d(14935011);
        Intrinsics.checkNotNullExpressionValue(aeVarD95, "rgb(...)");
        ae aeVarD96 = ae.d(3158064);
        Intrinsics.checkNotNullExpressionValue(aeVarD96, "rgb(...)");
        W = e.b(aeVarD95, aeVarD96);
        ae aeVarD97 = ae.d(13092807);
        Intrinsics.checkNotNullExpressionValue(aeVarD97, "rgb(...)");
        ae aeVarD98 = ae.d(6184542);
        Intrinsics.checkNotNullExpressionValue(aeVarD98, "rgb(...)");
        X = e.b(aeVarD97, aeVarD98);
        ae aeVar3 = new ae(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVar3, "argb(...)");
        ae aeVar4 = new ae(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVar4, "argb(...)");
        Y = e.b(aeVar3, aeVar4);
        ae aeVarD99 = ae.d(1672761);
        Intrinsics.checkNotNullExpressionValue(aeVarD99, "rgb(...)");
        ae aeVarD100 = ae.d(7198092);
        Intrinsics.checkNotNullExpressionValue(aeVarD100, "rgb(...)");
        Z = e.b(aeVarD99, aeVarD100);
        ae aeVarD101 = ae.d(12906192);
        Intrinsics.checkNotNullExpressionValue(aeVarD101, "rgb(...)");
        ae aeVarD102 = ae.d(2047784);
        Intrinsics.checkNotNullExpressionValue(aeVarD102, "rgb(...)");
        aa = e.b(aeVarD101, aeVarD102);
        ae aeVarD103 = ae.d(743376);
        Intrinsics.checkNotNullExpressionValue(aeVarD103, "rgb(...)");
        ae aeVarD104 = ae.d(11061242);
        Intrinsics.checkNotNullExpressionValue(aeVarD104, "rgb(...)");
        ab = e.b(aeVarD103, aeVarD104);
        ae aeVarD105 = ae.d(1797875);
        Intrinsics.checkNotNullExpressionValue(aeVarD105, "rgb(...)");
        ae aeVarD106 = ae.d(11061242);
        Intrinsics.checkNotNullExpressionValue(aeVarD106, "rgb(...)");
        ac = e.b(aeVarD105, aeVarD106);
        ae aeVarD107 = ae.d(25499);
        Intrinsics.checkNotNullExpressionValue(aeVarD107, "rgb(...)");
        ae aeVarD108 = ae.d(8376319);
        Intrinsics.checkNotNullExpressionValue(aeVarD108, "rgb(...)");
        ad = e.b(aeVarD107, aeVarD108);
        ae aeVarD109 = ae.d(743376);
        Intrinsics.checkNotNullExpressionValue(aeVarD109, "rgb(...)");
        ae aeVarD110 = ae.d(11061242);
        Intrinsics.checkNotNullExpressionValue(aeVarD110, "rgb(...)");
        ae = e.b(aeVarD109, aeVarD110);
        ae aeVarD111 = ae.d(11740702);
        Intrinsics.checkNotNullExpressionValue(aeVarD111, "rgb(...)");
        ae aeVarD112 = ae.d(15906997);
        Intrinsics.checkNotNullExpressionValue(aeVarD112, "rgb(...)");
        af = e.b(aeVarD111, aeVarD112);
        ae aeVarD113 = ae.d(9721600);
        Intrinsics.checkNotNullExpressionValue(aeVarD113, "rgb(...)");
        ae aeVarD114 = ae.d(16759593);
        Intrinsics.checkNotNullExpressionValue(aeVarD114, "rgb(...)");
        ag = e.b(aeVarD113, aeVarD114);
        ae aeVarD115 = ae.d(1338414);
        Intrinsics.checkNotNullExpressionValue(aeVarD115, "rgb(...)");
        ae aeVarD116 = ae.d(7198092);
        Intrinsics.checkNotNullExpressionValue(aeVarD116, "rgb(...)");
        ah = e.b(aeVarD115, aeVarD116);
        ae aeVarD117 = ae.d(15528958);
        Intrinsics.checkNotNullExpressionValue(aeVarD117, "rgb(...)");
        ae aeVarD118 = ae.d(2767187);
        Intrinsics.checkNotNullExpressionValue(aeVarD118, "rgb(...)");
        ai = e.b(aeVarD117, aeVarD118);
        ae aeVarD119 = ae.d(13886461);
        Intrinsics.checkNotNullExpressionValue(aeVarD119, "rgb(...)");
        ae aeVarD120 = ae.d(4280941);
        Intrinsics.checkNotNullExpressionValue(aeVarD120, "rgb(...)");
        aj = e.b(aeVarD119, aeVarD120);
        ae aeVarD121 = ae.d(13886461);
        Intrinsics.checkNotNullExpressionValue(aeVarD121, "rgb(...)");
        ae aeVarD122 = ae.d(4280941);
        Intrinsics.checkNotNullExpressionValue(aeVarD122, "rgb(...)");
        ak = e.b(aeVarD121, aeVarD122);
        ae aeVarD123 = ae.d(0);
        Intrinsics.checkNotNullExpressionValue(aeVarD123, "rgb(...)");
        ae aeVarD124 = ae.d(0);
        Intrinsics.checkNotNullExpressionValue(aeVarD124, "rgb(...)");
        al = e.b(aeVarD123, aeVarD124);
        ae aeVarD125 = ae.d(16759593);
        Intrinsics.checkNotNullExpressionValue(aeVarD125, "rgb(...)");
        ae aeVarD126 = ae.d(16759593);
        Intrinsics.checkNotNullExpressionValue(aeVarD126, "rgb(...)");
        am = e.b(aeVarD125, aeVarD126);
        ae aeVarD127 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD127, "rgb(...)");
        ((com.google.android.libraries.navigation.internal.jt.a) com.google.android.libraries.navigation.internal.ii.b.a(com.google.android.libraries.navigation.internal.jt.a.class)).g().a();
        ae aeVarD128 = ae.d(2105636);
        Intrinsics.checkNotNull(aeVarD128);
        an = e.b(aeVarD127, aeVarD128);
        ae aeVarD129 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD129, "rgb(...)");
        ae aeVarD130 = ae.d(3750201);
        Intrinsics.checkNotNullExpressionValue(aeVarD130, "rgb(...)");
        ao = e.b(aeVarD129, aeVarD130);
        ae aeVarD131 = ae.d(15791353);
        Intrinsics.checkNotNullExpressionValue(aeVarD131, "rgb(...)");
        ae aeVarD132 = ae.d(1974048);
        Intrinsics.checkNotNullExpressionValue(aeVarD132, "rgb(...)");
        ap = e.b(aeVarD131, aeVarD132);
        ae aeVarD133 = ae.d(14148847);
        Intrinsics.checkNotNullExpressionValue(aeVarD133, "rgb(...)");
        ae aeVarD134 = ae.d(3950673);
        Intrinsics.checkNotNullExpressionValue(aeVarD134, "rgb(...)");
        aq = e.b(aeVarD133, aeVarD134);
        ae aeVarD135 = ae.d(15331062);
        Intrinsics.checkNotNullExpressionValue(aeVarD135, "rgb(...)");
        ae aeVarD136 = ae.d(2632236);
        Intrinsics.checkNotNullExpressionValue(aeVarD136, "rgb(...)");
        ar = e.b(aeVarD135, aeVarD136);
        ae aeVarD137 = ae.d(14541802);
        Intrinsics.checkNotNullExpressionValue(aeVarD137, "rgb(...)");
        ae aeVarD138 = ae.d(3355959);
        Intrinsics.checkNotNullExpressionValue(aeVarD138, "rgb(...)");
        as = e.b(aeVarD137, aeVarD138);
        ae aeVarD139 = ae.d(16317181);
        Intrinsics.checkNotNullExpressionValue(aeVarD139, "rgb(...)");
        ae aeVarD140 = ae.d(1776411);
        Intrinsics.checkNotNullExpressionValue(aeVarD140, "rgb(...)");
        at = e.b(aeVarD139, aeVarD140);
        ae aeVarD141 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD141, "rgb(...)");
        ae aeVarD142 = ae.d(1250068);
        Intrinsics.checkNotNullExpressionValue(aeVarD142, "rgb(...)");
        au = e.b(aeVarD141, aeVarD142);
        ae aeVarD143 = ae.d(14148847);
        Intrinsics.checkNotNullExpressionValue(aeVarD143, "rgb(...)");
        ae aeVarD144 = ae.d(3950673);
        Intrinsics.checkNotNullExpressionValue(aeVarD144, "rgb(...)");
        av = e.b(aeVarD143, aeVarD144);
        ae aeVar5 = new ae(Color.argb(153, 0, 0, 0));
        Intrinsics.checkNotNullExpressionValue(aeVar5, "argb(...)");
        ae aeVar6 = new ae(Color.argb(153, 0, 0, 0));
        Intrinsics.checkNotNullExpressionValue(aeVar6, "argb(...)");
        aw = e.b(aeVar5, aeVar6);
        ae aeVarD145 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD145, "rgb(...)");
        ae aeVarD146 = ae.d(2697773);
        Intrinsics.checkNotNullExpressionValue(aeVarD146, "rgb(...)");
        ax = e.b(aeVarD145, aeVarD146);
        ae aeVarD147 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD147, "rgb(...)");
        ae aeVarD148 = ae.d(2961203);
        Intrinsics.checkNotNullExpressionValue(aeVarD148, "rgb(...)");
        ay = e.b(aeVarD147, aeVarD148);
        ae aeVarD149 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD149, "rgb(...)");
        ae aeVarD150 = ae.d(3224634);
        Intrinsics.checkNotNullExpressionValue(aeVarD150, "rgb(...)");
        az = e.b(aeVarD149, aeVarD150);
        ae aeVarD151 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD151, "rgb(...)");
        ae aeVarD152 = ae.d(3290684);
        Intrinsics.checkNotNullExpressionValue(aeVarD152, "rgb(...)");
        aA = e.b(aeVarD151, aeVarD152);
        ae aeVarD153 = ae.d(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVarD153, "rgb(...)");
        ae aeVarD154 = ae.d(3488064);
        Intrinsics.checkNotNullExpressionValue(aeVarD154, "rgb(...)");
        aB = e.b(aeVarD153, aeVarD154);
        ae aeVarD155 = ae.d(16448511);
        Intrinsics.checkNotNullExpressionValue(aeVarD155, "rgb(...)");
        ae aeVarD156 = ae.d(3224634);
        Intrinsics.checkNotNullExpressionValue(aeVarD156, "rgb(...)");
        aC = e.b(aeVarD155, aeVarD156);
        ae aeVar7 = new ae(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVar7, "argb(...)");
        ae aeVar8 = new ae(16777215);
        Intrinsics.checkNotNullExpressionValue(aeVar8, "argb(...)");
        aD = e.b(aeVar7, aeVar8);
    }
}
