package com.google.android.libraries.geo.mapcore.internal.legacy.vector.gl.drawable;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes2.dex */
public final class am {
    public final String a = "#define _a 1\n#define _b 2\n#define _c 2\n#define _d 1\n#define _e 3\n#define _f 2\n#define _g 0\nprecision highp float;uniform bool a;uniform float b,n,o,r;varying vec4 c,d,e,f,g,h,i;vec4 J(){return vec4(h.xy,e.zw);}uniform mat4 j;uniform ivec4 k[64],l[64*2];uniform vec2 m;attribute vec4 p;attribute vec4 q;uniform vec4 s;vec4 K(ivec2 t){vec4 u;u.a=floor(float(t.x)*(1./256.))*(1./255.);if(u.a!=0.){u.r=fract(float(t.x)*(1./256.))*(256./255.);u.b=fract(float(t.y)*(1./256.))*(256./255.);u.g=floor(float(t.y)*(1./256.))*(1./255.);}return u;}vec3 L(int t){vec3 u;u.z=fract(float(t)*(1./16.))*16.;float v=floor(float(t)*(1./16.));u.x=floor(v*(1./16.));u.y=fract(v*(1./16.))*16.;return u;}vec2 M(int t){vec2 u;u.x=floor(float(t)*(1./256.))+1.;u.y=fract(float(t)*(1./256.))*256.+1.;return u;}vec2 N(vec2 t,vec2 u){vec2 v,w,x,A,B;v=vec2(256.*o);w=mod(v,u);x=mod(m,u);A=mod(x*w,u);B=t*n*o;B.y=v.y-B.y;B+=A;return B;}void O(out vec4 t,out vec4 u){t.xy=vec2(l[int(q.r)*2].zw);u.xy=M(l[int(q.r)*2].y);t.zw=vec2(l[int(q.r)*2+1].zw);u.zw=M(l[int(q.r)*2+1].y);}void main(){ivec4 t=k[int(q.r)];ivec2 u=int(q.g)==1?t.zw:t.xy;float v,w;v=q.b/4.;w=q.a/4.;c=K(u);if(c.a==0.||b<v||b>w){gl_Position=vec4(0);return;}gl_Position=j*p;if(a&&q.g==0.){vec3 x,A;x=L(l[int(q.r)*2].x);A=L(l[int(q.r)*2+1].x);f=vec4(x.xy,A.xy);ivec3 B,C;B=ivec3(x+.5);C=ivec3(A+.5);bool D,E;D=B.x!=_g;E=C.x!=_g;if(D||E){O(d,e);float F=B.x==_f?s.y:1.;h.xy=e.xy*F;h.zw=(h.xy-e.xy)/2.;i.xy=e.x*e.y>0.?N(p.xy,e.xy):vec2(0);i.zw=e.z*e.w>0.?N(p.xy,e.zw):vec2(0);i*=vec4(vec2(F*4.),vec2(2.*4.));vec4 G,H;G=J()/2.;H=vec4(bvec4(B.z==_c,B.z==_d,C.z==_c,C.z==_d));g=G*H;i-=(1.-H)*G;bool I=B.x==_e||B.x==_f&&C.x!=_f;f.x=!D?0.:I?s.w:s.z;f.z=!E?0.:C.x==_e?r:s.x;}}}";
    public final String b = "#define _a 1\n#define _b 2\n#define _c 2\n#define _d 1\n#define _e 3\n#define _f 2\n#define _g 0\nprecision highp float;uniform bool a;varying vec4 c,d,e,f,g,h,i;vec4 C(){return vec4(h.xy,e.zw);}vec4 D(){return vec4(h.zw,vec2(0));}uniform sampler2D t;uniform vec2 u;vec4 E(){vec4 v,w,x;v=C();w=D();x=mod(floor(i/v),2.).yxwz*g;return mod(i-x,v)-w;}vec4 F(vec2 v,vec2 w,vec2 x){bvec4 A=bvec4(lessThan(x,vec2(0)),greaterThanEqual(x,w));if(any(A))return vec4(0);x=clamp(x,vec2(.5),w-.5);return texture2D(t,(v+x)*u);}vec4 G(vec4 v,vec3 w,int x){if(x==_a)v.rgb*=w;else if(x==_b)v.rgb=v.rgb+w.rgb*v.a-v.rgb*w.rgb;return v;}vec4 H(vec4 v,vec4 w){return v+(1.-v.a)*w;}vec4 I(vec3 v){vec4 w,x,A;w=E();x=vec4(0);if(f.x>0.){x=F(d.xy,e.xy,w.xy);int A=int(f.y+.5);x=G(x,v,A)*f.x;}A=vec4(0);if(f.z>0.){A=F(d.zw,e.zw,w.zw);int B=int(f.w+.5);A=G(A,v,B)*f.z;}return H(x,A);}void main(){vec3 v=c.rgb;if(a)if(f.x>0.||f.z>0.){vec4 w=I(v);v=H(w,vec4(v,1)).rgb;}gl_FragColor=vec4(v,c.a);}";
    public final al c = new al();
    public final ak d = new ak();
}
