package com.google.android.libraries.navigation.internal.qr;

import com.google.android.libraries.navigation.R;

/* JADX INFO: compiled from: PG */
/* JADX INFO: loaded from: classes7.dex */
public final class c {
    public static final int A;
    public static final int B;
    public static final int C;
    public static final int D;
    public static final int E;
    public static final int F;
    public static final int G;
    public static final int H;
    public static final int I;
    public static final int J;
    public static final int K;
    public static final int L;
    public static final int M;
    public static final int N;
    public static final int O;
    public static final int P;
    public static final int Q;
    public static final int R;
    public static final int S;
    public static final int T;
    public static final int U;
    public static final int V;
    public static final int W;
    public static final int X;
    public static final int Y;
    public static final int Z;
    public static final int a;
    public static final int aa;
    public static final int ab;
    public static final int ac;
    public static final int b;
    public static final int c;
    public static final int d;
    public static final int e;
    public static final int f;
    public static final int g;
    public static final int h;
    public static final int i;
    public static final int j;
    public static final int k;
    public static final int l;
    public static final int m;

    /* JADX INFO: renamed from: n, reason: collision with root package name */
    public static final int f559n;
    public static final int o;
    public static final int p;
    public static final int q;
    public static final int r;
    public static final int s;
    public static final int t;
    public static final int u;
    public static final int v;
    public static final int w;
    public static final int x;
    public static final int y;
    public static final int z;

    static {
        int i2 = R.drawable.abc_ab_share_pack_mtrl_alpha;
        a = R.drawable.blue_walking_alternate_dot;
        b = R.drawable.blue_walking_alternate_dot_dim;
        c = R.drawable.blue_walking_dot;
        d = R.drawable.blue_walking_dot_dim;
        e = R.drawable.blue_walking_dot_dim_map_colors2;
        f = R.drawable.blue_walking_dot_map_colors2;
        g = R.drawable.blue_walking_dot_night;
        h = R.drawable.blue_walking_dot_night_map_colors2;
        i = R.drawable.client_injected_default_cap;
        j = R.drawable.default_cap;
        k = R.drawable.ic_mod_transit_notice_alert;
        l = R.drawable.ic_mod_transit_notice_information;
        m = R.drawable.ic_mod_transit_notice_warning;
        f559n = R.drawable.ic_transit_notice_alert;
        o = R.drawable.ic_transit_notice_information;
        p = R.drawable.ic_transit_notice_warning;
        q = R.drawable.indeterminate_route_alternate_dot;
        r = R.drawable.indeterminate_route_alternate_dot_dim;
        s = R.drawable.indeterminate_route_dot;
        t = R.drawable.indeterminate_route_dot_dim;
        u = R.drawable.measle;
        v = R.drawable.measle_a;
        w = R.drawable.measle_b;
        x = R.drawable.measle_c;
        y = R.drawable.measle_d;
        z = R.drawable.measle_e;
        A = R.drawable.measle_f;
        B = R.drawable.measle_g;
        C = R.drawable.measle_h;
        D = R.drawable.measle_i;
        E = R.drawable.measle_j;
        F = R.drawable.measle_k;
        G = R.drawable.measle_l;
        H = R.drawable.measle_m;
        I = R.drawable.measle_n;
        J = R.drawable.measle_o;
        K = R.drawable.measle_p;
        L = R.drawable.measle_q;
        M = R.drawable.measle_r;
        N = R.drawable.measle_s;
        O = R.drawable.measle_t;
        P = R.drawable.measle_u;
        Q = R.drawable.measle_v;
        R = R.drawable.measle_w;
        S = R.drawable.measle_x;
        T = R.drawable.measle_y;
        U = R.drawable.measle_z;
        V = R.drawable.pin_a;
        W = R.drawable.pin_ad_purple;
        X = R.drawable.pin_b;
        Y = R.drawable.pin_directionscard;
        Z = R.drawable.pin_yellow;
        aa = R.drawable.startpoint_measle;
        ab = R.drawable.transitpoint_measle;
        ac = R.drawable.white_pixel;
    }
}
